#!/bin/bash
# echo "$0"
DIR="$( cd "$( dirname "$0" )" && pwd )"
if [ ! -e "../bin" ]
then
    mkdir ../bin/
fi
# Code of DIR from http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

# Code of escaping spaces from http://mindspill.net/computing/linux-notes/escape-spaces-with-sed/
#P="${DIR}/zr54/lexer/lexer.flex"
#echo $P
#Q=$(echo $P | sed 's/ /\\ /g')
#echo $Q
echo "Start processing lexer.flex"
#~/jflex/bin/jflex \"$Q\"
~/jflex/bin/jflex "${DIR}"/src/zr54/lexer/*.flex
echo "Done processing lexer.flex"
echo "Start processing xi.cup"
"${DIR}"/lib/cup  -destdir "${DIR}"/src/zr54/parser/ "${DIR}"/src/zr54/parser/xi.cup
echo "Done processing xi.cup"
echo "Start processing ixi.cup"
"${DIR}"/lib/cup  -destdir "${DIR}"/src/zr54/ixi/ "${DIR}"/src/zr54/ixi/ixi.cup
echo "Done processing ixi.cup"

echo "Start compiling .java files"
mkdir "${DIR}"/bin
javac -d "${DIR}"/bin -cp "${DIR}"/src:"${DIR}"/lib/java_cup.jar:"${DIR}"/lib/java-getopt-1.0.14.jar "${DIR}"/src/zr54/*/*.java "${DIR}"/src/polyglot/*/*.java  "${DIR}"/src/edu/cornell/cs/cs4120/*/*.java "${DIR}"/src/edu/cornell/cs/cs4120/xic/*/*.java "${DIR}"/src/edu/cornell/cs/cs4120/xic/ir/*/*.java
echo "Done compiling .java files"
