/* The following code was generated by JFlex 1.6.1 */

package zr54.lexer;
import zr54.parser.*;
import java_cup.runtime.*;
import java.io.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/vagrant/shared/cs5120/src/zr54/lexer/lexer.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARLITERAL = 4;
  public static final int DIGITS = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\65\1\66\1\1\22\0\1\3\1\56\1\11"+
    "\2\0\1\64\1\62\1\12\1\41\1\42\1\57\1\60\1\50\1\61"+
    "\1\52\1\4\1\7\1\10\10\17\1\51\1\47\1\55\1\53\1\54"+
    "\2\0\6\16\24\5\1\45\1\13\1\46\1\0\1\6\1\0\1\36"+
    "\1\20\1\35\1\37\1\23\1\30\1\34\1\33\1\25\1\5\1\40"+
    "\1\22\1\5\1\26\1\21\2\5\1\31\1\24\1\27\1\14\1\5"+
    "\1\32\1\15\2\5\1\43\1\63\1\44\7\0\1\65\u1fa2\0\1\65"+
    "\1\65\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\13\4\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\2\36"+
    "\1\37\1\40\1\1\2\41\1\42\1\1\3\43\1\2"+
    "\7\4\1\44\10\4\1\45\1\46\1\47\1\50\1\0"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\12\43\5\0\1\63\5\4\1\64\1\65"+
    "\7\4\1\66\1\67\1\70\1\71\4\0\1\72\1\73"+
    "\1\74\1\75\1\76\1\0\1\77\1\100\1\101\3\4"+
    "\1\102\1\103\1\104\5\4\3\0\1\105\2\4\1\106"+
    "\1\4\1\107\1\4\1\110\1\0\1\111\1\112\1\113"+
    "\1\4\1\114\1\4\1\0\1\115\1\4\1\116\1\117";

  private static int [] zzUnpackAction() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\334\0\u014a"+
    "\0\u0181\0\334\0\334\0\u01b8\0\334\0\334\0\u01ef\0\u0226"+
    "\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de"+
    "\0\u0415\0\334\0\334\0\334\0\334\0\334\0\334\0\334"+
    "\0\334\0\334\0\334\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528"+
    "\0\334\0\334\0\334\0\334\0\334\0\u055f\0\u0596\0\334"+
    "\0\334\0\u05cd\0\u0604\0\u063b\0\334\0\334\0\u0672\0\334"+
    "\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3\0\u082a"+
    "\0\u0861\0\u0898\0\u0181\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab"+
    "\0\u09e2\0\u0a19\0\u0a50\0\334\0\334\0\334\0\334\0\u0a87"+
    "\0\334\0\334\0\334\0\334\0\334\0\334\0\334\0\334"+
    "\0\334\0\334\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1"+
    "\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u06a9\0\u0d1b\0\u06e0"+
    "\0\u0d52\0\u0181\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0181"+
    "\0\u0181\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6"+
    "\0\334\0\334\0\334\0\334\0\u101d\0\u0b63\0\u0b9a\0\u1054"+
    "\0\334\0\334\0\334\0\334\0\334\0\u108b\0\334\0\u10c2"+
    "\0\u0181\0\u10f9\0\u1130\0\u1167\0\u0181\0\u0181\0\u0181\0\u119e"+
    "\0\u11d5\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u0181"+
    "\0\u1356\0\u138d\0\u0181\0\u13c4\0\u0181\0\u13fb\0\u0181\0\u1432"+
    "\0\334\0\334\0\u0181\0\u1469\0\u0181\0\u14a0\0\u14d7\0\u0181"+
    "\0\u150e\0\334\0\u0181";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\2\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\5\1\17\2\11\1\14\1\20\1\11"+
    "\1\21\1\22\1\11\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\11\1\31\3\11\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\5\1\7\1\56\1\57\1\60\6\56\1\61\1\56"+
    "\1\62\53\56\1\63\1\64\1\65\7\63\1\66\1\67"+
    "\53\63\14\70\1\71\1\72\51\70\71\0\1\7\70\0"+
    "\1\73\67\0\4\11\1\0\1\11\1\0\25\11\35\0"+
    "\2\14\6\0\1\14\54\0\4\11\1\0\1\11\1\0"+
    "\10\11\1\74\14\11\33\0\4\11\1\0\1\11\1\0"+
    "\5\11\1\75\7\11\1\76\7\11\33\0\4\11\1\0"+
    "\1\11\1\0\7\11\1\77\15\11\33\0\4\11\1\0"+
    "\1\11\1\0\1\11\1\100\4\11\1\101\16\11\33\0"+
    "\4\11\1\0\1\11\1\0\12\11\1\102\1\11\1\103"+
    "\10\11\33\0\4\11\1\0\1\11\1\0\7\11\1\104"+
    "\15\11\33\0\4\11\1\0\1\11\1\0\15\11\1\105"+
    "\1\11\1\106\5\11\33\0\4\11\1\0\1\11\1\0"+
    "\22\11\1\107\2\11\33\0\4\11\1\0\1\11\1\0"+
    "\7\11\1\110\15\11\33\0\4\11\1\0\1\11\1\0"+
    "\17\11\1\111\5\11\33\0\4\11\1\0\1\11\1\0"+
    "\5\11\1\112\1\113\16\11\101\0\1\114\66\0\1\115"+
    "\66\0\1\116\66\0\1\117\67\0\1\120\12\0\1\56"+
    "\2\0\6\56\1\0\1\56\1\0\53\56\2\0\1\60"+
    "\64\0\1\5\2\0\6\5\1\121\1\122\1\123\2\124"+
    "\2\5\1\125\5\5\1\126\1\127\1\130\1\131\33\5"+
    "\14\0\1\132\56\0\1\65\64\0\1\70\2\0\6\70"+
    "\1\133\1\134\1\135\1\136\1\137\2\70\1\140\5\70"+
    "\1\141\1\142\1\143\1\144\33\70\11\0\2\145\3\0"+
    "\1\146\1\0\3\145\2\0\1\145\4\0\1\145\4\0"+
    "\3\145\36\0\2\147\4\0\1\150\3\151\2\0\1\151"+
    "\4\0\1\151\4\0\3\151\27\0\1\73\1\6\1\7"+
    "\64\73\5\0\4\11\1\0\1\11\1\0\7\11\1\152"+
    "\15\11\33\0\4\11\1\0\1\11\1\0\5\11\1\153"+
    "\17\11\33\0\4\11\1\0\1\11\1\0\7\11\1\154"+
    "\15\11\33\0\4\11\1\0\1\11\1\0\12\11\1\155"+
    "\12\11\33\0\4\11\1\0\1\11\1\0\13\11\1\156"+
    "\11\11\33\0\4\11\1\0\1\11\1\0\10\11\1\157"+
    "\14\11\33\0\4\11\1\0\1\11\1\0\13\11\1\160"+
    "\11\11\33\0\4\11\1\0\1\11\1\0\16\11\1\161"+
    "\6\11\33\0\4\11\1\0\1\11\1\0\1\162\24\11"+
    "\33\0\4\11\1\0\1\11\1\0\11\11\1\163\13\11"+
    "\33\0\4\11\1\0\1\11\1\0\6\11\1\164\16\11"+
    "\33\0\4\11\1\0\1\11\1\0\13\11\1\165\11\11"+
    "\33\0\4\11\1\0\1\11\1\0\11\11\1\166\13\11"+
    "\33\0\4\11\1\0\1\11\1\0\12\11\1\167\12\11"+
    "\33\0\4\11\1\0\1\11\1\0\22\11\1\170\2\11"+
    "\102\0\1\171\24\0\1\172\66\0\1\173\66\0\1\174"+
    "\63\0\2\175\3\0\1\176\1\0\3\175\2\0\1\175"+
    "\4\0\1\175\4\0\3\175\44\0\1\177\3\200\2\0"+
    "\1\200\4\0\1\200\4\0\3\200\41\0\1\201\66\0"+
    "\1\202\66\0\1\203\66\0\1\204\66\0\1\205\63\0"+
    "\2\206\5\0\3\206\2\0\1\206\4\0\1\206\4\0"+
    "\3\206\36\0\2\207\5\0\3\207\2\0\1\207\4\0"+
    "\1\207\4\0\3\207\36\0\2\210\5\0\3\210\2\0"+
    "\1\210\4\0\1\210\4\0\3\210\34\0\4\11\1\0"+
    "\1\11\1\0\6\11\1\211\16\11\33\0\4\11\1\0"+
    "\1\11\1\0\22\11\1\212\2\11\33\0\4\11\1\0"+
    "\1\11\1\0\20\11\1\213\4\11\33\0\4\11\1\0"+
    "\1\11\1\0\7\11\1\214\15\11\33\0\4\11\1\0"+
    "\1\11\1\0\7\11\1\215\15\11\33\0\4\11\1\0"+
    "\1\11\1\0\7\11\1\216\15\11\33\0\4\11\1\0"+
    "\1\11\1\0\10\11\1\217\14\11\33\0\4\11\1\0"+
    "\1\11\1\0\10\11\1\220\14\11\33\0\4\11\1\0"+
    "\1\11\1\0\1\221\24\11\33\0\4\11\1\0\1\11"+
    "\1\0\6\11\1\222\16\11\33\0\4\11\1\0\1\11"+
    "\1\0\13\11\1\223\11\11\33\0\4\11\1\0\1\11"+
    "\1\0\10\11\1\224\14\11\35\0\2\225\5\0\3\225"+
    "\2\0\1\225\4\0\1\225\4\0\3\225\36\0\2\226"+
    "\5\0\3\226\2\0\1\226\4\0\1\226\4\0\3\226"+
    "\36\0\2\227\5\0\3\227\2\0\1\227\4\0\1\227"+
    "\4\0\3\227\45\0\3\151\2\0\1\151\4\0\1\151"+
    "\4\0\3\151\34\0\4\11\1\0\1\11\1\0\24\11"+
    "\1\230\33\0\4\11\1\0\1\11\1\0\13\11\1\231"+
    "\11\11\33\0\4\11\1\0\1\11\1\0\12\11\1\232"+
    "\12\11\33\0\4\11\1\0\1\11\1\0\7\11\1\233"+
    "\15\11\33\0\4\11\1\0\1\11\1\0\15\11\1\234"+
    "\7\11\33\0\4\11\1\0\1\11\1\0\7\11\1\235"+
    "\15\11\33\0\4\11\1\0\1\11\1\0\11\11\1\236"+
    "\13\11\33\0\4\11\1\0\1\11\1\0\10\11\1\237"+
    "\14\11\35\0\2\240\5\0\3\240\2\0\1\240\4\0"+
    "\1\240\4\0\3\240\41\0\1\241\63\0\2\242\5\0"+
    "\3\242\2\0\1\242\4\0\1\242\4\0\3\242\34\0"+
    "\4\11\1\0\1\11\1\0\17\11\1\243\5\11\33\0"+
    "\4\11\1\0\1\11\1\0\23\11\1\244\1\11\33\0"+
    "\4\11\1\0\1\11\1\0\12\11\1\245\12\11\33\0"+
    "\4\11\1\0\1\11\1\0\12\11\1\246\12\11\35\0"+
    "\2\247\5\0\3\247\2\0\1\247\4\0\1\247\4\0"+
    "\3\247\34\0\4\11\1\0\1\11\1\0\10\11\1\250"+
    "\14\11\33\0\4\11\1\0\1\11\1\0\1\251\24\11"+
    "\40\0\1\252\61\0\4\11\1\0\1\11\1\0\7\11"+
    "\1\253\15\11\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5445];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\1\1\1\11\2\1\2\11\1\1\2\11"+
    "\13\1\12\11\5\1\5\11\2\1\2\11\3\1\2\11"+
    "\1\1\1\11\23\1\4\11\1\0\12\11\12\1\5\0"+
    "\17\1\4\11\4\0\5\11\1\0\1\11\15\1\3\0"+
    "\10\1\1\0\2\11\4\1\1\0\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  
  /* store a reference to the parser object */
  private BufferedWriter bw;
  private boolean even, error;
  private int start_line, start_column; //For string location
  private String errorMessage;
  
  StringBuilder string = new StringBuilder();
  
  private Symbol symbol(int type, Object value) {
  	Symbol symObj = new Symbol(type, yyline+1, yycolumn+1, value);
    return new Symbol(type, yyline+1, yycolumn+1, symObj);
  }
  
  private Symbol symbol(int type, Object value, int spec_line, int spec_column) {
  	Symbol symObj = new Symbol(type, spec_line+1, spec_column+1, value);
    return new Symbol(type, spec_line+1, spec_column+1, symObj);
  }

  public int getLine(){
    return yyline;
  }
  public int getColumn(){
    return yycolumn;
  }
  
  private char unicodeChar() {
    int r = 0;

    for (int k = zzMarkedPos-4; k < zzMarkedPos; k++) {
      int c = zzBuffer[k];
	  
      if (c >= 'a') 
        c-= 'a'-10;
      else if (c >= 'A')
        c-= 'A'-10;
      else
        c-= '0';

      r <<= 4;
      r += c;
    }
   
    return (char) r;
  }


  private char singleUnicodeChar() {
    int r = 0;

    for (int k = zzMarkedPos-5; k < zzMarkedPos-1; k++) {
      int c = zzBuffer[k];
	  
      if (c >= 'a') 
        c-= 'a'-10;
      else if (c >= 'A')
        c-= 'A'-10;
      else
        c-= '0';

      r <<= 4;
      r += c;
    }
   
    return (char) r;
  }

    private char singleASCIIChar() {
    int r = 0;

    for (int k = zzMarkedPos-3; k < zzMarkedPos-1; k++) {
      int c = zzBuffer[k];
	  
      if (c >= 'a') 
        c-= 'a'-10;
      else if (c >= 'A')
        c-= 'A'-10;
      else
        c-= '0';

      r <<= 4;
      r += c;
    }
   
    return (char) r;
  }

  private String ASCIIString(int startPos) {
      
    StringBuilder output = new StringBuilder();
    
    
    for (int k = zzMarkedPos-startPos; k < zzMarkedPos; k+=2) {
      
      int r = 0;
      
      for(int j = 0; j < 2; j++)
      {
      	  int c = zzBuffer[k+j];
          if (c >= 'a') 
        	c-= 'a'-10;
      	  else if (c >= 'A')
        	c-= 'A'-10;
      	  else
        	c-= '0';
      	  r <<= 4;
      	  r += c;
      }
      
      output.append((char) r);
      
    }
    return output.toString();
    
  }
  
  public String getErrorMessage() {
    if (error) {
      return errorMessage;
    } else {
      return null;
    }
  }
  


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 176) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case DIGITS: {
              errorMessage = (start_line+1)+":"+(start_column+1)+" error:Illegal escape sequence \""+yytext()+"\"\n";
    				 error = true;
    				 return symbol(sym.EOF, null);
            }
            case 172: break;
            default:
              {
                return symbol(sym.EOF, null);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { errorMessage = (yyline+1)+":"+(yycolumn+1)+" error:Illegal escape sequence \""+yytext()+"\"\n";
    				 error = true;
    				 return symbol(sym.EOF, null);
            }
          case 80: break;
          case 2: 
            { /* ignore */
            }
          case 81: break;
          case 3: 
            { return symbol(sym.DIV, "/");
            }
          case 82: break;
          case 4: 
            { return symbol(sym.IDENTIFIER, yytext());
            }
          case 83: break;
          case 5: 
            { return symbol(sym.UNDERSCORE, "_");
            }
          case 84: break;
          case 6: 
            { return symbol(sym.INTEGER_LITERAL, yytext());
            }
          case 85: break;
          case 7: 
            { start_line = yyline; 
  								   start_column = yycolumn;
  								   yybegin(STRING); 
  								   string.setLength(0);
            }
          case 86: break;
          case 8: 
            { start_line = yyline; 
  								   start_column = yycolumn;
  								   yybegin(CHARLITERAL);
            }
          case 87: break;
          case 9: 
            { return symbol(sym.LPAREN, "(");
            }
          case 88: break;
          case 10: 
            { return symbol(sym.RPAREN, ")");
            }
          case 89: break;
          case 11: 
            { return symbol(sym.LBRACE, "{");
            }
          case 90: break;
          case 12: 
            { return symbol(sym.RBRACE, "}");
            }
          case 91: break;
          case 13: 
            { return symbol(sym.LBRACK, "[");
            }
          case 92: break;
          case 14: 
            { return symbol(sym.RBRACK, "]");
            }
          case 93: break;
          case 15: 
            { return symbol(sym.SEMICOLON, ";");
            }
          case 94: break;
          case 16: 
            { return symbol(sym.COMMA, ",");
            }
          case 95: break;
          case 17: 
            { return symbol(sym.COLON, ":");
            }
          case 96: break;
          case 18: 
            { return symbol(sym.DOT, ".");
            }
          case 97: break;
          case 19: 
            { return symbol(sym.EQ, "=");
            }
          case 98: break;
          case 20: 
            { return symbol(sym.GT, ">");
            }
          case 99: break;
          case 21: 
            { return symbol(sym.LT, "<");
            }
          case 100: break;
          case 22: 
            { return symbol(sym.NOT, "!");
            }
          case 101: break;
          case 23: 
            { return symbol(sym.MULT, "*");
            }
          case 102: break;
          case 24: 
            { return symbol(sym.PLUS, "+");
            }
          case 103: break;
          case 25: 
            { return symbol(sym.MINUS, "-");
            }
          case 104: break;
          case 26: 
            { return symbol(sym.AND, "&");
            }
          case 105: break;
          case 27: 
            { return symbol(sym.OR, "|");
            }
          case 106: break;
          case 28: 
            { return symbol(sym.MOD, "%");
            }
          case 107: break;
          case 29: 
            { string.append( yytext() );
            }
          case 108: break;
          case 30: 
            { errorMessage = (yyline+1)+":"+(yycolumn+1)+" error:Unterminated string at end of line\n";
    				 error = true;
    				 return symbol(sym.EOF, null);
            }
          case 109: break;
          case 31: 
            { yybegin(YYINITIAL); 
  								   return symbol(sym.STRING_LITERAL, string.toString(), start_line, start_column);
            }
          case 110: break;
          case 32: 
            { even = false; string.append("\\");
            }
          case 111: break;
          case 33: 
            { errorMessage = (start_line+1)+":"+(start_column+1)+" error:Unterminated string at end of line\n";
    				 error = true;
    				 return symbol(sym.EOF, null);
            }
          case 112: break;
          case 34: 
            { errorMessage = (start_line+1)+":"+(start_column+1)+" error:empty character literal\n";
    				 error = true;
    				 return symbol(sym.EOF, null);
            }
          case 113: break;
          case 35: 
            { errorMessage = (start_line+1)+":"+(start_column+1)+" error:Illegal escape sequence \""+yytext()+"\"\n";
    				 error = true;
    				 return symbol(sym.EOF, null);
            }
          case 114: break;
          case 36: 
            { return symbol(sym.IF, "if");
            }
          case 115: break;
          case 37: 
            { return symbol(sym.EQEQ, "==");
            }
          case 116: break;
          case 38: 
            { return symbol(sym.GTEQ, ">=");
            }
          case 117: break;
          case 39: 
            { return symbol(sym.LTEQ, "<=");
            }
          case 118: break;
          case 40: 
            { return symbol(sym.NOTEQ, "!=");
            }
          case 119: break;
          case 41: 
            { string.append( "\\\"" );
            }
          case 120: break;
          case 42: 
            { string.append( "\\'" );
            }
          case 121: break;
          case 43: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 1);
            { even = !even; string.append("\\\\");
            }
          case 122: break;
          case 44: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 1);
            { if (even) {
                                       even = false;
                       				   string.append("\\");
                     				}
                     				else
                       					yybegin(DIGITS);
            }
          case 123: break;
          case 45: 
            { string.append( "\\b" );
            }
          case 124: break;
          case 46: 
            { string.append( "\\n" );
            }
          case 125: break;
          case 47: 
            { string.append( "\\t" );
            }
          case 126: break;
          case 48: 
            { string.append( "\\f" );
            }
          case 127: break;
          case 49: 
            { string.append( "\\r" );
            }
          case 128: break;
          case 50: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, yytext().charAt(0), start_line, start_column);
            }
          case 129: break;
          case 51: 
            { return symbol(sym.USE, "use");
            }
          case 130: break;
          case 52: 
            { return symbol(sym.INT, "int");
            }
          case 131: break;
          case 53: 
            { return symbol(sym.NEW, "new");
            }
          case 132: break;
          case 54: 
            { return symbol(sym.HIGHMULT, "*>>");
            }
          case 133: break;
          case 55: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, '\"', start_line, start_column);
            }
          case 134: break;
          case 56: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, '\'', start_line, start_column);
            }
          case 135: break;
          case 57: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, '\\', start_line, start_column);
            }
          case 136: break;
          case 58: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, '\b', start_line, start_column);
            }
          case 137: break;
          case 59: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, '\n', start_line, start_column);
            }
          case 138: break;
          case 60: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, '\t', start_line, start_column);
            }
          case 139: break;
          case 61: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, '\f', start_line, start_column);
            }
          case 140: break;
          case 62: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, '\r', start_line, start_column);
            }
          case 141: break;
          case 63: 
            { string.append("\\").append( yytext() ); yybegin(STRING);
            }
          case 142: break;
          case 64: 
            { string.append(ASCIIString(yytext().length()-1)); yybegin(STRING);
            }
          case 143: break;
          case 65: 
            { return symbol(sym.BOOL, "bool");
            }
          case 144: break;
          case 66: 
            { return symbol(sym.ELSE, "else");
            }
          case 145: break;
          case 67: 
            { return symbol(sym.BOOLEAN_LITERAL, "true");
            }
          case 146: break;
          case 68: 
            { return symbol(sym.THIS, "this");
            }
          case 147: break;
          case 69: 
            { return symbol(sym.BREAK, "break");
            }
          case 148: break;
          case 70: 
            { return symbol(sym.BOOLEAN_LITERAL, "false");
            }
          case 149: break;
          case 71: 
            { return symbol(sym.WHILE, "while");
            }
          case 150: break;
          case 72: 
            { return symbol(sym.CLASS, "class");
            }
          case 151: break;
          case 73: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, singleASCIIChar(), start_line, start_column);
            }
          case 152: break;
          case 74: 
            { string.append(unicodeChar()); yybegin(STRING);
            }
          case 153: break;
          case 75: 
            { return symbol(sym.LENGTH, "length");
            }
          case 154: break;
          case 76: 
            { return symbol(sym.RETURN, "return");
            }
          case 155: break;
          case 77: 
            { return symbol(sym.EXTENDS, "extends");
            }
          case 156: break;
          case 78: 
            { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, singleUnicodeChar(), start_line, start_column);
            }
          case 157: break;
          case 79: 
            { return symbol(sym.CONTINUE, "continue");
            }
          case 158: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
