/* Part of code from http://www2.cs.tum.edu/projekte/cup/examples.php */
package zr54.ixi;

import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*;
import zr54.lexer.*;
import zr54.parser.*;
import zr54.typechecker.Type;

parser code {:
    public CodeWriterSExpPrinter printer;
    public parser(CodeWriterSExpPrinter printer){ this.printer=printer; }

    @Override
    public void syntax_error(Symbol cur_token){
        if (cur_token.value!=null){
        	Symbol tok = (Symbol) cur_token.value;
            printer.printAtom(cur_token.left + ":" +
                cur_token.right + " error:Unexpected token " + tok.value);
        } else{
            printer.printAtom(cur_token.left + ":" + cur_token.right +
            " error:Unexpected token " + LexerOutput.terminalName.get(cur_token.sym));
        }
    }
:}
/* NEVER DELETE ANY TERMINALS EVEN IF THERE ARE WARNINGS THAT THEY ARE NEVER USED!!! */
terminal Symbol IDENTIFIER, INTEGER_LITERAL, STRING_LITERAL, CHARACTER_LITERAL, BOOLEAN_LITERAL,
         LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK, SEMICOLON, COMMA, COLON, EQ,
         GT, LT, NOT, MULT, PLUS, MINUS, AND, OR, MOD, IF, EQEQ, GTEQ, LTEQ, NOTEQ,
         HIGHMULT, INT, BOOL, ELSE, WHILE, LENGTH, RETURN, DIV, USE, UNDERSCORE, LRBRACK;

nonterminal AstNode arrayType, type, argumentWithType, argumentsWithType, optionalArgumentsWithType, functionReturnType, typesList, bracket, brackets, methods, method, optionalSemicolon;
          

precedence nonassoc ELSE;
precedence nonassoc EQ;
precedence left OR;
precedence left AND;
precedence left EQEQ, NOTEQ;
precedence left LT, LTEQ, GTEQ, GT;
precedence left PLUS, MINUS;
precedence left MULT, HIGHMULT, DIV, MOD;
precedence nonassoc NOT;


start with methods;



arrayType           ::= INT:i brackets:bs    {: bs.addChildLeftMost(new TypeNode("INT", i)); RESULT = bs; :}
                      | BOOL:b brackets:bs   {: bs.addChildLeftMost(new TypeNode("BOOL", b)); RESULT = bs; :}
                      ;


bracket             ::= LBRACK RBRACK                {: RESULT = new TypeNode("bracket", new Symbol(sym.LRBRACK, "[]"), new DefaultNode("", null));  :}
                      ;

brackets            ::= bracket:b brackets:bs   {: RESULT = new TypeNode("brackets", new Symbol(sym.LRBRACK, "[]"), bs); RESULT.addGrandChildren(b); :}
                      | bracket:b               {: RESULT = b; :}
                      ;

type                ::= arrayType:a     {: RESULT = a; :}
                      | INT:i             {: RESULT = new TypeNode("INT", i); :}
                      | BOOL:b            {: RESULT = new TypeNode("BOOL", b); :}
                      ;

argumentWithType    ::= IDENTIFIER:id COLON type:t  {: RESULT = new DeclarationNode("argumentWithType", id, t); :}
                      ;

argumentsWithType   ::= argumentsWithType:as COMMA argumentWithType:a {: RESULT = new DefaultNode("argumentsWithType", null); RESULT.addGrandChildren(as); RESULT.addChild(a); :}
                      | argumentWithType:a                            {: RESULT = new DefaultNode("argumentsWithType", null, a); :}
                      ;



functionReturnType  ::= COLON typesList:tl    {: RESULT = new DefaultNode("functionReturnType", null); RESULT.addGrandChildren(tl); :}
                      |                       {: RESULT = new DefaultNode("forceParen", null); :}
                      ;

typesList           ::= typesList:tl COMMA type:t   {: RESULT = new DefaultNode("typesList", null); RESULT.addGrandChildren(tl); RESULT.addChild(t); :}
                      | type:t                      {: RESULT = new DefaultNode("typesList", null); RESULT.addChild(t); :}
                      ;


method              ::= IDENTIFIER:id LPAREN optionalArgumentsWithType:a RPAREN functionReturnType:r 
                        {: RESULT = new MethodNode("method", id);
                           RESULT.addChild(a); RESULT.addChild(r); :}
                      ;



optionalArgumentsWithType ::=  argumentsWithType:a {: RESULT = a; :}
                            |                      {: RESULT = new DefaultNode("forceParen", null); :}
                            ;





optionalSemicolon   ::= SEMICOLON
                      |
                      ;








methods             ::= methods:ms method:m   {: RESULT = new DefaultNode("methods", null); RESULT.addGrandChildren(ms); RESULT.addChild(m); :}
                      | method:m              {: RESULT = new DefaultNode("methods", null, m); :}
                      ;


