
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package zr54.ixi;

import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*;
import zr54.lexer.*;
import zr54.parser.*;
import zr54.typechecker.Type;
import zr54.main.XiException;

/** CUP v0.11b 20150326 generated parser.
  */
public class parser
 extends java_cup.runtime.lr_parser {

  @Override
  public final Class<?> getSymbolContainer() {
    return sym.class;
  }

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner and a SymbolFactory. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\042\000\002\002\004\000\002\016\007\000\002\016" +
    "\011\000\002\016\010\000\002\016\006\000\002\020\004" +
    "\000\002\020\003\000\002\017\007\000\002\002\004\000" +
    "\002\002\004\000\002\002\004\000\002\011\004\000\002" +
    "\012\004\000\002\012\003\000\002\003\003\000\002\003" +
    "\003\000\002\003\003\000\002\003\003\000\002\004\005" +
    "\000\002\005\005\000\002\005\003\000\002\007\004\000" +
    "\002\007\006\000\002\007\002\000\002\010\005\000\002" +
    "\010\003\000\002\014\007\000\002\014\003\000\002\006" +
    "\003\000\002\006\002\000\002\015\003\000\002\015\002" +
    "\000\002\013\004\000\002\013\003" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\070\000\006\004\010\054\007\001\002\000\010\002" +
    "\uffe0\004\uffe0\054\uffe0\001\002\000\010\002\072\004\010" +
    "\054\007\001\002\000\010\002\uffe6\004\uffe6\054\uffe6\001" +
    "\002\000\004\004\047\001\002\000\004\011\011\001\002" +
    "\000\006\004\014\012\uffe4\001\002\000\004\012\035\001" +
    "\002\000\006\012\uffed\020\uffed\001\002\000\004\021\020" +
    "\001\002\000\006\012\uffe5\020\016\001\002\000\004\004" +
    "\014\001\002\000\006\012\uffee\020\uffee\001\002\000\010" +
    "\004\023\042\025\043\022\001\002\000\016\002\ufff3\004" +
    "\ufff3\012\ufff3\014\ufff3\020\ufff3\054\ufff3\001\002\000\020" +
    "\002\ufff1\004\ufff1\012\ufff1\014\ufff1\015\026\020\ufff1\054" +
    "\ufff1\001\002\000\020\002\ufff0\004\ufff0\012\ufff0\014\ufff0" +
    "\015\026\020\ufff0\054\ufff0\001\002\000\006\012\uffef\020" +
    "\uffef\001\002\000\020\002\ufff2\004\ufff2\012\ufff2\014\ufff2" +
    "\015\026\020\ufff2\054\ufff2\001\002\000\004\016\032\001" +
    "\002\000\020\002\ufff4\004\ufff4\012\ufff4\014\ufff4\015\026" +
    "\020\ufff4\054\ufff4\001\002\000\016\002\ufff9\004\ufff9\012" +
    "\ufff9\014\ufff9\020\ufff9\054\ufff9\001\002\000\016\002\ufff5" +
    "\004\ufff5\012\ufff5\014\ufff5\020\ufff5\054\ufff5\001\002\000" +
    "\020\002\ufff6\004\ufff6\012\ufff6\014\ufff6\015\ufff6\020\ufff6" +
    "\054\ufff6\001\002\000\016\002\ufff7\004\ufff7\012\ufff7\014" +
    "\ufff7\020\ufff7\054\ufff7\001\002\000\016\002\ufff8\004\ufff8" +
    "\012\ufff8\014\ufff8\020\ufff8\054\ufff8\001\002\000\012\002" +
    "\uffea\004\uffea\021\036\054\uffea\001\002\000\012\004\023" +
    "\011\040\042\025\043\022\001\002\000\010\002\uffe7\004" +
    "\uffe7\054\uffe7\001\002\000\010\004\023\042\025\043\022" +
    "\001\002\000\014\002\uffec\004\uffec\014\uffec\020\043\054" +
    "\uffec\001\002\000\016\002\uffe8\004\uffe8\012\uffe8\014\uffe8" +
    "\020\uffe8\054\uffe8\001\002\000\010\004\023\042\025\043" +
    "\022\001\002\000\016\002\uffe9\004\uffe9\012\uffe9\014\uffe9" +
    "\020\uffe9\054\uffe9\001\002\000\006\012\046\020\043\001" +
    "\002\000\012\002\uffeb\004\uffeb\014\uffeb\054\uffeb\001\002" +
    "\000\006\013\051\057\050\001\002\000\004\004\064\001" +
    "\002\000\006\004\054\014\053\001\002\000\006\004\ufffb" +
    "\014\ufffb\001\002\000\010\002\ufffd\004\ufffd\054\ufffd\001" +
    "\002\000\004\011\060\001\002\000\006\004\054\014\057" +
    "\001\002\000\006\004\ufffc\014\ufffc\001\002\000\010\002" +
    "\000\004\000\054\000\001\002\000\006\004\014\012\uffe4" +
    "\001\002\000\004\012\062\001\002\000\010\004\uffea\014" +
    "\uffea\021\036\001\002\000\006\004\ufffa\014\ufffa\001\002" +
    "\000\004\013\065\001\002\000\006\004\054\014\066\001" +
    "\002\000\010\002\ufffe\004\ufffe\054\ufffe\001\002\000\006" +
    "\004\054\014\070\001\002\000\010\002\uffff\004\uffff\054" +
    "\uffff\001\002\000\010\002\uffe1\004\uffe1\054\uffe1\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() {return _action_table;}

  /** {@code reduce_goto} table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\070\000\010\013\004\014\003\016\005\001\001\000" +
    "\002\001\001\000\006\014\070\016\005\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\004" +
    "\012\005\014\006\011\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\016\001\001\000\002\001\001\000\006\002\020\003\023" +
    "\001\001\000\002\001\001\000\006\011\026\012\033\001" +
    "\001\000\006\011\026\012\032\001\001\000\002\001\001" +
    "\000\006\011\026\012\027\001\001\000\002\001\001\000" +
    "\006\011\026\012\030\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\036\001\001\000\010\002\020\003\041" +
    "\010\040\001\001\000\002\001\001\000\010\002\020\003" +
    "\041\010\044\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\002\020\003\043\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\017\051\020\054\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\017\055" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\004" +
    "\012\005\014\006\060\001\001\000\002\001\001\000\004" +
    "\007\062\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\017\051\020\066\001\001\000\002\001\001\000\004" +
    "\017\055\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to {@code reduce_goto} table. */
  @Override
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack<java_cup.runtime.Symbol> stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 0;}

  /** {@code EOF} Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** {@code error} Symbol index. */
  @Override
  public int error_sym() {return 1;}



    public CodeWriterSExpPrinter printer;
    public parser(CodeWriterSExpPrinter printer, String file){ this.printer = printer; this.file = file;}
    public String file;
    
    @Override
    public void syntax_error(Symbol cur_token){
    try{
     String errorMessage = ((Lexer)this.getScanner()).getErrorMessage();
      if(errorMessage != null) {
            
            XiException e = new XiException(cur_token, errorMessage, "Lexical");
            
//             writer.write(e.getLine()+":"+e.getColumn()+" error:"+e.getMessage());
             printer.printAtom(e.errorMessage(file));
           throw e;
          }
        if (cur_token.value!=null){
        	Symbol tok = (Symbol) cur_token.value;
            printer.printAtom(cur_token.left + ":" +
                cur_token.right + " error:Unexpected token " + tok.value);
        } else{
            printer.printAtom(cur_token.left + ":" + cur_token.right +
            " error:Unexpected token " + LexerOutput.terminalName.get(cur_token.sym));
        }
        }
      catch(XiException e) {
      //printer.printAtom(e.errorMessage(file));
        System.out.println(e.errorMessage(file));
      }
    }


/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
    private final parser parser;

    /** Constructor */
    CUP$parser$actions(parser parser) {
        this.parser = parser;
    }

    /** Method with the actual generated action code for actions 0 to 33. */
    public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            /* Symbol object for return from actions */
            java_cup.runtime.Symbol CUP$parser$result;

        /* select the action based on the action number */
        switch (CUP$parser$act_num) {
        /*. . . . . . . . . . . . . . . . . . . .*/
        case 0: // $START ::= methods EOF 
            {
                Object RESULT = null;
                int start_valleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int start_valright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode start_val = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                RESULT = start_val;
                CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            /* ACCEPT */
            CUP$parser$parser.done_parsing();
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 1: // classDef ::= CLASS IDENTIFIER LBRACE classMethods RBRACE 
            {
                AstNode RESULT = null;
                int cleft = CUP$parser$stack.elementAt(CUP$parser$top-4).left;
                int cright = CUP$parser$stack.elementAt(CUP$parser$top-4).right;
                Symbol c = CUP$parser$stack.elementAt(CUP$parser$top-4).<Symbol> value();
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-3).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-3).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-3).<Symbol> value();
                int lbleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int lbright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                Symbol lb = CUP$parser$stack.elementAt(CUP$parser$top-2).<Symbol> value();
                int fmleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int fmright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode fm = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                int rbleft = CUP$parser$stack.peek().left;
                int rbright = CUP$parser$stack.peek().right;
                Symbol rb = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new ClassNode("classDef", id); RESULT.addGrandChildren(fm); ((ClassNode) RESULT).findMethodsAndFields(); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("classDef",12, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 2: // classDef ::= CLASS IDENTIFIER EXTENDS IDENTIFIER LBRACE classMethods RBRACE 
            {
                AstNode RESULT = null;
                int cleft = CUP$parser$stack.elementAt(CUP$parser$top-6).left;
                int cright = CUP$parser$stack.elementAt(CUP$parser$top-6).right;
                Symbol c = CUP$parser$stack.elementAt(CUP$parser$top-6).<Symbol> value();
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-5).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-5).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-5).<Symbol> value();
                int sleft = CUP$parser$stack.elementAt(CUP$parser$top-3).left;
                int sright = CUP$parser$stack.elementAt(CUP$parser$top-3).right;
                Symbol s = CUP$parser$stack.elementAt(CUP$parser$top-3).<Symbol> value();
                int lbleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int lbright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                Symbol lb = CUP$parser$stack.elementAt(CUP$parser$top-2).<Symbol> value();
                int fmleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int fmright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode fm = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                int rbleft = CUP$parser$stack.peek().left;
                int rbright = CUP$parser$stack.peek().right;
                Symbol rb = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new ClassNode("classDef", id); RESULT.addChild(new ClassNameNode("className", s)); RESULT.addGrandChildren(fm); ((ClassNode) RESULT).findMethodsAndFields(); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("classDef",12, CUP$parser$stack.elementAt(CUP$parser$top-6), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 3: // classDef ::= CLASS IDENTIFIER EXTENDS IDENTIFIER LBRACE RBRACE 
            {
                AstNode RESULT = null;
                int cleft = CUP$parser$stack.elementAt(CUP$parser$top-5).left;
                int cright = CUP$parser$stack.elementAt(CUP$parser$top-5).right;
                Symbol c = CUP$parser$stack.elementAt(CUP$parser$top-5).<Symbol> value();
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-4).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-4).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-4).<Symbol> value();
                int sleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int sright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                Symbol s = CUP$parser$stack.elementAt(CUP$parser$top-2).<Symbol> value();
                int lbleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int lbright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Symbol lb = CUP$parser$stack.elementAt(CUP$parser$top-1).<Symbol> value();
                int rbleft = CUP$parser$stack.peek().left;
                int rbright = CUP$parser$stack.peek().right;
                Symbol rb = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new ClassNode("classDef", id); RESULT.addChild(new ClassNameNode("className", s)); ((ClassNode) RESULT).findMethodsAndFields(); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("classDef",12, CUP$parser$stack.elementAt(CUP$parser$top-5), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 4: // classDef ::= CLASS IDENTIFIER LBRACE RBRACE 
            {
                AstNode RESULT = null;
                int cleft = CUP$parser$stack.elementAt(CUP$parser$top-3).left;
                int cright = CUP$parser$stack.elementAt(CUP$parser$top-3).right;
                Symbol c = CUP$parser$stack.elementAt(CUP$parser$top-3).<Symbol> value();
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-2).<Symbol> value();
                int lbleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int lbright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Symbol lb = CUP$parser$stack.elementAt(CUP$parser$top-1).<Symbol> value();
                int rbleft = CUP$parser$stack.peek().left;
                int rbright = CUP$parser$stack.peek().right;
                Symbol rb = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new ClassNode("classDef", id); ((ClassNode) RESULT).findMethodsAndFields(); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("classDef",12, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 5: // classMethods ::= classMethods classMethod 
            {
                AstNode RESULT = null;
                int fmleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int fmright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode fm = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                int mleft = CUP$parser$stack.peek().left;
                int mright = CUP$parser$stack.peek().right;
                AstNode m = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("classMethods", null); RESULT.addGrandChildren(fm); RESULT.addChild(m); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("classMethods",14, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 6: // classMethods ::= classMethod 
            {
                AstNode RESULT = null;
                int mleft = CUP$parser$stack.peek().left;
                int mright = CUP$parser$stack.peek().right;
                AstNode m = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("classMethods", null, m); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("classMethods",14, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 7: // classMethod ::= IDENTIFIER LPAREN optionalArgumentsWithType RPAREN functionReturnType 
            {
                AstNode RESULT = null;
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-4).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-4).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-4).<Symbol> value();
                int aleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int aright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                AstNode a = CUP$parser$stack.elementAt(CUP$parser$top-2).<AstNode> value();
                int rleft = CUP$parser$stack.peek().left;
                int rright = CUP$parser$stack.peek().right;
                AstNode r = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new ClassMethodNode("classMethod", id);
                           RESULT.addChild(a); RESULT.addChild(r);
                CUP$parser$result = parser.getSymbolFactory().newSymbol("classMethod",13, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 8: // arrayType ::= INT brackets 
            {
                AstNode RESULT = null;
                int ileft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int iright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Symbol i = CUP$parser$stack.elementAt(CUP$parser$top-1).<Symbol> value();
                int bsleft = CUP$parser$stack.peek().left;
                int bsright = CUP$parser$stack.peek().right;
                AstNode bs = CUP$parser$stack.peek().<AstNode> value();
                 bs.addChildLeftMost(new TypeNode("INT", i)); RESULT = bs; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 9: // arrayType ::= BOOL brackets 
            {
                AstNode RESULT = null;
                int bleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int bright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Symbol b = CUP$parser$stack.elementAt(CUP$parser$top-1).<Symbol> value();
                int bsleft = CUP$parser$stack.peek().left;
                int bsright = CUP$parser$stack.peek().right;
                AstNode bs = CUP$parser$stack.peek().<AstNode> value();
                 bs.addChildLeftMost(new TypeNode("BOOL", b)); RESULT = bs; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 10: // arrayType ::= IDENTIFIER brackets 
            {
                AstNode RESULT = null;
                int tleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int tright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Symbol t = CUP$parser$stack.elementAt(CUP$parser$top-1).<Symbol> value();
                int bsleft = CUP$parser$stack.peek().left;
                int bsright = CUP$parser$stack.peek().right;
                AstNode bs = CUP$parser$stack.peek().<AstNode> value();
                 bs.addChildLeftMost(new TypeNode("IDENTIFIER", t)); RESULT = bs; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 11: // bracket ::= LBRACK RBRACK 
            {
                AstNode RESULT = null;
                 RESULT = new TypeNode("bracket", new Symbol(sym.LRBRACK, "[]"), new DefaultNode("", null));  
                CUP$parser$result = parser.getSymbolFactory().newSymbol("bracket",7, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 12: // brackets ::= bracket brackets 
            {
                AstNode RESULT = null;
                int bleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int bright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode b = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                int bsleft = CUP$parser$stack.peek().left;
                int bsright = CUP$parser$stack.peek().right;
                AstNode bs = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new TypeNode("brackets", new Symbol(sym.LRBRACK, "[]"), bs); RESULT.addGrandChildren(b); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",8, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 13: // brackets ::= bracket 
            {
                AstNode RESULT = null;
                int bleft = CUP$parser$stack.peek().left;
                int bright = CUP$parser$stack.peek().right;
                AstNode b = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = b; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",8, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 14: // type ::= arrayType 
            {
                AstNode RESULT = null;
                int aleft = CUP$parser$stack.peek().left;
                int aright = CUP$parser$stack.peek().right;
                AstNode a = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = a; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",1, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 15: // type ::= INT 
            {
                AstNode RESULT = null;
                int ileft = CUP$parser$stack.peek().left;
                int iright = CUP$parser$stack.peek().right;
                Symbol i = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new TypeNode("INT", i); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",1, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 16: // type ::= BOOL 
            {
                AstNode RESULT = null;
                int bleft = CUP$parser$stack.peek().left;
                int bright = CUP$parser$stack.peek().right;
                Symbol b = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new TypeNode("BOOL", b); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",1, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 17: // type ::= IDENTIFIER 
            {
                AstNode RESULT = null;
                int tleft = CUP$parser$stack.peek().left;
                int tright = CUP$parser$stack.peek().right;
                Symbol t = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new TypeNode("IDENTIFIER", t); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",1, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 18: // argumentWithType ::= IDENTIFIER COLON type 
            {
                AstNode RESULT = null;
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-2).<Symbol> value();
                int tleft = CUP$parser$stack.peek().left;
                int tright = CUP$parser$stack.peek().right;
                AstNode t = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DeclarationNode("argumentWithType", id, t); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentWithType",2, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 19: // argumentsWithType ::= argumentsWithType COMMA argumentWithType 
            {
                AstNode RESULT = null;
                int asleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int asright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                AstNode as = CUP$parser$stack.elementAt(CUP$parser$top-2).<AstNode> value();
                int aleft = CUP$parser$stack.peek().left;
                int aright = CUP$parser$stack.peek().right;
                AstNode a = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("argumentsWithType", null); RESULT.addGrandChildren(as); RESULT.addChild(a); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",3, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 20: // argumentsWithType ::= argumentWithType 
            {
                AstNode RESULT = null;
                int aleft = CUP$parser$stack.peek().left;
                int aright = CUP$parser$stack.peek().right;
                AstNode a = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("argumentsWithType", null, a); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",3, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 21: // functionReturnType ::= COLON typesList 
            {
                AstNode RESULT = null;
                int tlleft = CUP$parser$stack.peek().left;
                int tlright = CUP$parser$stack.peek().right;
                AstNode tl = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("functionReturnType", null); RESULT.addGrandChildren(tl); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",5, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 22: // functionReturnType ::= COLON LPAREN typesList RPAREN 
            {
                AstNode RESULT = null;
                int tlleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int tlright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode tl = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                 RESULT = new DefaultNode("functionReturnType", null); RESULT.addGrandChildren(tl); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",5, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 23: // functionReturnType ::= 
            {
                AstNode RESULT = null;
                 RESULT = new DefaultNode("forceParen", null); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",5, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 24: // typesList ::= typesList COMMA type 
            {
                AstNode RESULT = null;
                int tlleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int tlright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                AstNode tl = CUP$parser$stack.elementAt(CUP$parser$top-2).<AstNode> value();
                int tleft = CUP$parser$stack.peek().left;
                int tright = CUP$parser$stack.peek().right;
                AstNode t = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("typesList", null); RESULT.addGrandChildren(tl); RESULT.addChild(t); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",6, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 25: // typesList ::= type 
            {
                AstNode RESULT = null;
                int tleft = CUP$parser$stack.peek().left;
                int tright = CUP$parser$stack.peek().right;
                AstNode t = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("typesList", null); RESULT.addChild(t); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 26: // method ::= IDENTIFIER LPAREN optionalArgumentsWithType RPAREN functionReturnType 
            {
                AstNode RESULT = null;
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-4).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-4).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-4).<Symbol> value();
                int aleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int aright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                AstNode a = CUP$parser$stack.elementAt(CUP$parser$top-2).<AstNode> value();
                int rleft = CUP$parser$stack.peek().left;
                int rright = CUP$parser$stack.peek().right;
                AstNode r = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new MethodNode("method", id);
                           RESULT.addChild(a); RESULT.addChild(r); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("method",10, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 27: // method ::= classDef 
            {
                AstNode RESULT = null;
                int cdleft = CUP$parser$stack.peek().left;
                int cdright = CUP$parser$stack.peek().right;
                AstNode cd = CUP$parser$stack.peek().<AstNode> value();
                 RESULT =  cd; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("method",10, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 28: // optionalArgumentsWithType ::= argumentsWithType 
            {
                AstNode RESULT = null;
                int aleft = CUP$parser$stack.peek().left;
                int aright = CUP$parser$stack.peek().right;
                AstNode a = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = a; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("optionalArgumentsWithType",4, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 29: // optionalArgumentsWithType ::= 
            {
                AstNode RESULT = null;
                 RESULT = new DefaultNode("forceParen", null); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("optionalArgumentsWithType",4, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 30: // optionalSemicolon ::= SEMICOLON 
            {
                AstNode RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("optionalSemicolon",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 31: // optionalSemicolon ::= 
            {
                AstNode RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("optionalSemicolon",11, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 32: // methods ::= methods method 
            {
                AstNode RESULT = null;
                int msleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int msright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode ms = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                int mleft = CUP$parser$stack.peek().left;
                int mright = CUP$parser$stack.peek().right;
                AstNode m = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("methods", null); RESULT.addGrandChildren(ms); RESULT.addChild(m); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("methods",9, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 33: // methods ::= method 
            {
                AstNode RESULT = null;
                int mleft = CUP$parser$stack.peek().left;
                int mright = CUP$parser$stack.peek().right;
                AstNode m = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("methods", null, m); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("methods",9, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /* . . . . . .*/
        default:
            throw new Exception(
                  "Invalid action number " + CUP$parser$act_num + " found in internal parse table");

        }
    } /* end of method */

    /** Method splitting the generated action code into several parts. */
    public final java_cup.runtime.Symbol CUP$parser$do_action(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            return CUP$parser$do_action_part00000000(
                           CUP$parser$act_num,
                           CUP$parser$parser,
                           CUP$parser$stack,
                           CUP$parser$top);
    }
}

}
