
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package zr54.ixi;

import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*;
import zr54.lexer.*;
import zr54.parser.*;
import zr54.typechecker.Type;

/** CUP v0.11b 20150326 generated parser.
  */
public class parser
 extends java_cup.runtime.lr_parser {

  @Override
  public final Class<?> getSymbolContainer() {
    return sym.class;
  }

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner and a SymbolFactory. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\027\000\002\002\004\000\002\002\004\000\002\002" +
    "\004\000\002\011\004\000\002\012\004\000\002\012\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\004\005\000\002\005\005\000\002\005\003\000\002" +
    "\007\004\000\002\007\002\000\002\010\005\000\002\010" +
    "\003\000\002\014\007\000\002\006\003\000\002\006\002" +
    "\000\002\015\003\000\002\015\002\000\002\013\004\000" +
    "\002\013\003" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\037\000\004\004\006\001\002\000\006\002\uffeb\004" +
    "\uffeb\001\002\000\006\002\041\004\006\001\002\000\004" +
    "\011\007\001\002\000\006\004\012\012\uffef\001\002\000" +
    "\004\012\031\001\002\000\006\012\ufff6\020\ufff6\001\002" +
    "\000\004\021\016\001\002\000\006\012\ufff0\020\014\001" +
    "\002\000\004\004\012\001\002\000\006\012\ufff7\020\ufff7" +
    "\001\002\000\006\042\022\043\020\001\002\000\012\002" +
    "\ufffb\004\ufffb\012\ufffb\020\ufffb\001\002\000\014\002\ufff9" +
    "\004\ufff9\012\ufff9\015\023\020\ufff9\001\002\000\006\012" +
    "\ufff8\020\ufff8\001\002\000\014\002\ufffa\004\ufffa\012\ufffa" +
    "\015\023\020\ufffa\001\002\000\004\016\027\001\002\000" +
    "\014\002\ufffc\004\ufffc\012\ufffc\015\023\020\ufffc\001\002" +
    "\000\012\002\000\004\000\012\000\020\000\001\002\000" +
    "\012\002\ufffd\004\ufffd\012\ufffd\020\ufffd\001\002\000\014" +
    "\002\ufffe\004\ufffe\012\ufffe\015\ufffe\020\ufffe\001\002\000" +
    "\012\002\uffff\004\uffff\012\uffff\020\uffff\001\002\000\010" +
    "\002\ufff4\004\ufff4\021\033\001\002\000\006\002\ufff1\004" +
    "\ufff1\001\002\000\006\042\022\043\020\001\002\000\010" +
    "\002\ufff5\004\ufff5\020\036\001\002\000\010\002\ufff2\004" +
    "\ufff2\020\ufff2\001\002\000\006\042\022\043\020\001\002" +
    "\000\010\002\ufff3\004\ufff3\020\ufff3\001\002\000\006\002" +
    "\uffec\004\uffec\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() {return _action_table;}

  /** {@code reduce_goto} table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\037\000\006\013\004\014\003\001\001\000\002\001" +
    "\001\000\004\014\037\001\001\000\002\001\001\000\010" +
    "\004\010\005\012\006\007\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\014\001\001\000\002\001\001\000\006\002\016\003" +
    "\020\001\001\000\002\001\001\000\006\011\023\012\027" +
    "\001\001\000\002\001\001\000\006\011\023\012\024\001" +
    "\001\000\002\001\001\000\006\011\023\012\025\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\007\031\001\001\000\002\001\001" +
    "\000\010\002\016\003\034\010\033\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\002\016\003\036\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to {@code reduce_goto} table. */
  @Override
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack<java_cup.runtime.Symbol> stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 0;}

  /** {@code EOF} Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** {@code error} Symbol index. */
  @Override
  public int error_sym() {return 1;}



    public CodeWriterSExpPrinter printer;
    public parser(CodeWriterSExpPrinter printer){ this.printer=printer; }

    @Override
    public void syntax_error(Symbol cur_token){
        if (cur_token.value!=null){
        	Symbol tok = (Symbol) cur_token.value;
            printer.printAtom(cur_token.left + ":" +
                cur_token.right + " error:Unexpected token " + tok.value);
        } else{
            printer.printAtom(cur_token.left + ":" + cur_token.right +
            " error:Unexpected token " + LexerOutput.terminalName.get(cur_token.sym));
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
    private final parser parser;

    /** Constructor */
    CUP$parser$actions(parser parser) {
        this.parser = parser;
    }

    /** Method with the actual generated action code for actions 0 to 22. */
    public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            /* Symbol object for return from actions */
            java_cup.runtime.Symbol CUP$parser$result;

        /* select the action based on the action number */
        switch (CUP$parser$act_num) {
        /*. . . . . . . . . . . . . . . . . . . .*/
        case 0: // $START ::= methods EOF 
            {
                Object RESULT = null;
                int start_valleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int start_valright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode start_val = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                RESULT = start_val;
                CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            /* ACCEPT */
            CUP$parser$parser.done_parsing();
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 1: // arrayType ::= INT brackets 
            {
                AstNode RESULT = null;
                int ileft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int iright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Symbol i = CUP$parser$stack.elementAt(CUP$parser$top-1).<Symbol> value();
                int bsleft = CUP$parser$stack.peek().left;
                int bsright = CUP$parser$stack.peek().right;
                AstNode bs = CUP$parser$stack.peek().<AstNode> value();
                 bs.addChildLeftMost(new DefaultNode("INT", i)); RESULT = bs; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 2: // arrayType ::= BOOL brackets 
            {
                AstNode RESULT = null;
                int bleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int bright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Symbol b = CUP$parser$stack.elementAt(CUP$parser$top-1).<Symbol> value();
                int bsleft = CUP$parser$stack.peek().left;
                int bsright = CUP$parser$stack.peek().right;
                AstNode bs = CUP$parser$stack.peek().<AstNode> value();
                 bs.addChildLeftMost(new DefaultNode("BOOL", b)); RESULT = bs; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 3: // bracket ::= LBRACK RBRACK 
            {
                AstNode RESULT = null;
                 RESULT = new DefaultNode("bracket", new Symbol(sym.LRBRACK, "[]"), new DefaultNode("", null));  
                CUP$parser$result = parser.getSymbolFactory().newSymbol("bracket",7, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 4: // brackets ::= bracket brackets 
            {
                AstNode RESULT = null;
                int bleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int bright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode b = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                int bsleft = CUP$parser$stack.peek().left;
                int bsright = CUP$parser$stack.peek().right;
                AstNode bs = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("brackets", new Symbol(sym.LRBRACK, "[]"), bs); RESULT.addGrandChildren(b); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",8, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 5: // brackets ::= bracket 
            {
                AstNode RESULT = null;
                int bleft = CUP$parser$stack.peek().left;
                int bright = CUP$parser$stack.peek().right;
                AstNode b = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = b; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",8, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 6: // type ::= arrayType 
            {
                AstNode RESULT = null;
                int aleft = CUP$parser$stack.peek().left;
                int aright = CUP$parser$stack.peek().right;
                AstNode a = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = a; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",1, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 7: // type ::= INT 
            {
                AstNode RESULT = null;
                int ileft = CUP$parser$stack.peek().left;
                int iright = CUP$parser$stack.peek().right;
                Symbol i = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new DefaultNode("INT", i); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",1, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 8: // type ::= BOOL 
            {
                AstNode RESULT = null;
                int bleft = CUP$parser$stack.peek().left;
                int bright = CUP$parser$stack.peek().right;
                Symbol b = CUP$parser$stack.peek().<Symbol> value();
                 RESULT = new DefaultNode("BOOL", b); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",1, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 9: // argumentWithType ::= IDENTIFIER COLON type 
            {
                AstNode RESULT = null;
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-2).<Symbol> value();
                int tleft = CUP$parser$stack.peek().left;
                int tright = CUP$parser$stack.peek().right;
                AstNode t = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DeclarationNode("argumentWithType", id, t); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentWithType",2, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 10: // argumentsWithType ::= argumentsWithType COMMA argumentWithType 
            {
                AstNode RESULT = null;
                int asleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int asright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                AstNode as = CUP$parser$stack.elementAt(CUP$parser$top-2).<AstNode> value();
                int aleft = CUP$parser$stack.peek().left;
                int aright = CUP$parser$stack.peek().right;
                AstNode a = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("argumentsWithType", null); RESULT.addGrandChildren(as); RESULT.addChild(a); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",3, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 11: // argumentsWithType ::= argumentWithType 
            {
                AstNode RESULT = null;
                int aleft = CUP$parser$stack.peek().left;
                int aright = CUP$parser$stack.peek().right;
                AstNode a = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("argumentsWithType", null, a); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",3, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 12: // functionReturnType ::= COLON typesList 
            {
                AstNode RESULT = null;
                int tlleft = CUP$parser$stack.peek().left;
                int tlright = CUP$parser$stack.peek().right;
                AstNode tl = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("functionReturnType", null); RESULT.addGrandChildren(tl); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",5, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 13: // functionReturnType ::= 
            {
                AstNode RESULT = null;
                 RESULT = new DefaultNode("forceParen", null); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",5, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 14: // typesList ::= typesList COMMA type 
            {
                AstNode RESULT = null;
                int tlleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int tlright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                AstNode tl = CUP$parser$stack.elementAt(CUP$parser$top-2).<AstNode> value();
                int tleft = CUP$parser$stack.peek().left;
                int tright = CUP$parser$stack.peek().right;
                AstNode t = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("typesList", null); RESULT.addGrandChildren(tl); RESULT.addChild(t); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",6, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 15: // typesList ::= type 
            {
                AstNode RESULT = null;
                int tleft = CUP$parser$stack.peek().left;
                int tright = CUP$parser$stack.peek().right;
                AstNode t = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("typesList", null); RESULT.addChild(t); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 16: // method ::= IDENTIFIER LPAREN optionalArgumentsWithType RPAREN functionReturnType 
            {
                AstNode RESULT = null;
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-4).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-4).right;
                Symbol id = CUP$parser$stack.elementAt(CUP$parser$top-4).<Symbol> value();
                int aleft = CUP$parser$stack.elementAt(CUP$parser$top-2).left;
                int aright = CUP$parser$stack.elementAt(CUP$parser$top-2).right;
                AstNode a = CUP$parser$stack.elementAt(CUP$parser$top-2).<AstNode> value();
                int rleft = CUP$parser$stack.peek().left;
                int rright = CUP$parser$stack.peek().right;
                AstNode r = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("method", id);
                           RESULT.addChild(a); RESULT.addChild(r); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("method",10, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 17: // optionalArgumentsWithType ::= argumentsWithType 
            {
                AstNode RESULT = null;
                int aleft = CUP$parser$stack.peek().left;
                int aright = CUP$parser$stack.peek().right;
                AstNode a = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = a; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("optionalArgumentsWithType",4, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 18: // optionalArgumentsWithType ::= 
            {
                AstNode RESULT = null;
                 RESULT = new DefaultNode("forceParen", null); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("optionalArgumentsWithType",4, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 19: // optionalSemicolon ::= SEMICOLON 
            {
                AstNode RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("optionalSemicolon",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 20: // optionalSemicolon ::= 
            {
                AstNode RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("optionalSemicolon",11, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 21: // methods ::= methods method 
            {
                AstNode RESULT = null;
                int msleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int msright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                AstNode ms = CUP$parser$stack.elementAt(CUP$parser$top-1).<AstNode> value();
                int mleft = CUP$parser$stack.peek().left;
                int mright = CUP$parser$stack.peek().right;
                AstNode m = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("methods", null); RESULT.addGrandChildren(ms); RESULT.addChild(m); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("methods",9, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 22: // methods ::= method 
            {
                AstNode RESULT = null;
                int mleft = CUP$parser$stack.peek().left;
                int mright = CUP$parser$stack.peek().right;
                AstNode m = CUP$parser$stack.peek().<AstNode> value();
                 RESULT = new DefaultNode("methods", null, m); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("methods",9, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /* . . . . . .*/
        default:
            throw new Exception(
                  "Invalid action number " + CUP$parser$act_num + " found in internal parse table");

        }
    } /* end of method */

    /** Method splitting the generated action code into several parts. */
    public final java_cup.runtime.Symbol CUP$parser$do_action(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            return CUP$parser$do_action_part00000000(
                           CUP$parser$act_num,
                           CUP$parser$parser,
                           CUP$parser$stack,
                           CUP$parser$top);
    }
}

}
