package zr54.parser;

import zr54.main.XiException;
import zr54.typechecker.ClassDefination;
import zr54.typechecker.ClassSymbolTable;
import zr54.typechecker.FuncSignature;
import zr54.typechecker.FuncSymbolTable;
import zr54.typechecker.Type;
import zr54.typechecker.VarSymbolTable;
import java_cup.runtime.*;

import java.util.*;

import edu.cornell.cs.cs4120.xic.ir.*;


//when generated by the parser, the first child is class identifier, and the rest are fields and methods
public class ClassNode extends AstNode{
	
	ArrayList<ClassMethodNode> methods = new ArrayList<ClassMethodNode>();
	ArrayList<AstNode> fields = new ArrayList<AstNode>();
	ClassNameNode superClass = null;
	
	public ClassNode(String t, Symbol v) {
		super(t, v);
	}
	
	@Override
	public Type typeCheck(VarSymbolTable vars, FuncSymbolTable funcs, ClassSymbolTable classes, String currClass, boolean insideWhile)
			throws XiException {
		// TODO Auto-generated method stub
		// not finished!
				return new Type();
	}

	@Override
	public void generateIR(FuncSymbolTable funcs, ClassSymbolTable classes, String currClass, WhileStmtNode currWhile) {
		for(AstNode child : children)
			child.generateIR(funcs, classes, (String) symbol.value, currWhile);
		IRCompUnit irClass = new IRCompUnit("_CLASS_" + (String) symbol.value);
		for(ClassMethodNode method : methods)  {
			irClass.appendFunc((IRFuncDecl) method.irNode);
		}
		this.irNode = irClass;
	}

	@Override
	public boolean isConst() {
		// TODO Auto-generated method stub
		return false;
	}

	public void findMethodsAndFields() {
		for(AstNode child : children) {
			if(child instanceof ClassMethodNode) {
				methods.add((ClassMethodNode)child);
			}
			else if(child instanceof ClassNameNode) {
				superClass = (ClassNameNode) child;
			}
			else {
				fields.add(child);
			}

		}
	}
	
	@Override
	public void registerClassSignature(ClassSymbolTable classes) throws XiException {
		ClassDefination classSig = new ClassDefination((String)symbol.value);
		
		for(ClassMethodNode method : methods) {
			method.registerClassMethodSignature(classSig, classes, (String)this.symbol.value);
		}
		
		for(AstNode field : fields) {
			if(field instanceof DeclarationNode) {
				TypeNode t = (TypeNode) field.children.get(0);
				classSig.addField((String) field.symbol.value, t.typeCheck(new VarSymbolTable(), new FuncSymbolTable(), classes, (String)this.symbol.value, false));
			}
			else if(field instanceof MultiDeclarationNode) {
				AstNode vars = field.children.get(0);
				Type t = field.children.get(1).typeCheck(new VarSymbolTable(), new FuncSymbolTable(), classes, (String)this.symbol.value, false); 
				for(AstNode var : vars.children) {
					classSig.addField((String)var.symbol.value, t);					
				}
			}
		}
		
		classSig.determineIndices();
		classes.addClass((String)symbol.value, classSig);
	} 
	
}
