package zr54.parser;

import zr54.main.XiException;
import zr54.typechecker.ClassDefination;
import zr54.typechecker.ClassSymbolTable;
import zr54.typechecker.FuncSignature;
import zr54.typechecker.FuncSymbolTable;
import zr54.typechecker.Type;
import zr54.typechecker.VarSymbolTable;
import java_cup.runtime.*;

import java.util.*;


//when generated by the parser, the first child is class identifier, and the rest are fields and methods
public class ClassNode extends AstNode{
	
	ArrayList<ClassMethodNode> methods = new ArrayList<ClassMethodNode>();
	ArrayList<ClassFieldNode> fields = new ArrayList<ClassFieldNode>();
	ClassNameNode superClass = null;
	
	public ClassNode(String t, Symbol v) {
		super(t, v);
	}
	
	@Override
	public Type typeCheck(VarSymbolTable vars, FuncSymbolTable funcs)
			throws XiException {
		// TODO Auto-generated method stub
		// not finished!
				return new Type();
	}

	@Override
	public void generateIR(FuncSymbolTable funcs) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public boolean isConst() {
		// TODO Auto-generated method stub
		return false;
	}

	public void findMethodsAndFields() {
		for(AstNode child : children) {
			if(child instanceof ClassMethodNode) {
				methods.add((ClassMethodNode)child);
			}
			else if(child instanceof ClassFieldNode) {
				fields.add((ClassFieldNode)child);
			}
			else if(child instanceof ClassNameNode) {
				superClass = (ClassNameNode) child;
			}
		}
	}
	
	@Override
	public void registerClassSignature(ClassSymbolTable classes) throws XiException {
		ClassDefination classSig = new ClassDefination((String)symbol.value);
		
		for(ClassMethodNode method : methods) {
			method.registerClassMethodSignature(classSig.getFuncTable());
		}
		
		classes.addClass((String)symbol.value, classSig);
	} 
	
}
