
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package zr54.parser;

import zr54.lexer.*;
import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*;

/** CUP v0.11b 20150326 generated parser.
  */
public class parser
 extends java_cup.runtime.lr_parser {

  @Override
  public final Class<?> getSymbolContainer() {
    return sym.class;
  }

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner and a SymbolFactory. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\077\000\002\002\004\000\002\003\004\000\002\004" +
    "\007\000\002\005\003\000\002\005\003\000\002\006\005" +
    "\000\002\007\005\000\002\007\003\000\002\010\003\000" +
    "\002\010\003\000\002\010\003\000\002\010\003\000\002" +
    "\010\003\000\002\010\003\000\002\011\005\000\002\011" +
    "\003\000\002\012\004\000\002\012\006\000\002\012\002" +
    "\000\002\021\005\000\002\021\003\000\002\013\012\000" +
    "\002\014\004\000\002\014\003\000\002\015\003\000\002" +
    "\015\003\000\002\015\003\000\002\015\003\000\002\015" +
    "\004\000\002\015\004\000\002\015\005\000\002\025\003" +
    "\000\002\025\003\000\002\025\003\000\002\025\003\000" +
    "\002\025\003\000\002\025\003\000\002\025\003\000\002" +
    "\025\003\000\002\025\003\000\002\025\003\000\002\025" +
    "\003\000\002\025\003\000\002\025\003\000\002\025\003" +
    "\000\002\025\003\000\002\023\011\000\002\023\007\000" +
    "\002\027\003\000\002\027\005\000\002\024\011\000\002" +
    "\022\005\000\002\026\005\000\002\026\005\000\002\026" +
    "\003\000\002\026\004\000\002\026\004\000\002\016\006" +
    "\000\002\002\003\000\002\017\004\000\002\017\003\000" +
    "\002\020\003\000\002\020\003" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\152\000\006\004\012\052\006\001\002\000\010\002" +
    "\uffc4\004\uffc4\052\uffc4\001\002\000\010\002\uffc7\004\012" +
    "\052\006\001\002\000\004\004\153\001\002\000\010\002" +
    "\uffc3\004\uffc3\052\uffc3\001\002\000\010\002\uffc5\004\uffc5" +
    "\052\uffc5\001\002\000\004\002\152\001\002\000\004\012" +
    "\013\001\002\000\004\004\015\001\002\000\006\013\ufffa" +
    "\021\ufffa\001\002\000\004\022\150\001\002\000\006\013" +
    "\020\021\017\001\002\000\004\004\015\001\002\000\006" +
    "\014\uffef\022\021\001\002\000\006\012\133\043\135\001" +
    "\002\000\004\014\023\001\002\000\012\004\033\035\035" +
    "\046\032\050\025\001\002\000\016\004\uffe6\015\uffe6\035" +
    "\uffe6\045\uffe6\046\uffe6\050\uffe6\001\002\000\022\004\050" +
    "\006\047\007\046\010\043\011\042\012\045\026\040\031" +
    "\051\001\002\000\020\004\uffe8\015\uffe8\020\127\035\uffe8" +
    "\045\uffe8\046\uffe8\050\uffe8\001\002\000\016\004\uffe9\015" +
    "\uffe9\035\uffe9\045\uffe9\046\uffe9\050\uffe9\001\002\000\014" +
    "\004\033\015\126\035\035\046\032\050\025\001\002\000" +
    "\014\004\uffea\015\uffea\035\uffea\046\uffea\050\uffea\001\002" +
    "\000\004\012\120\001\002\000\006\012\074\023\116\001" +
    "\002\000\016\004\uffe7\015\uffe7\035\uffe7\045\uffe7\046\uffe7" +
    "\050\uffe7\001\002\000\004\012\036\001\002\000\022\004" +
    "\050\006\047\007\046\010\043\011\042\012\045\026\040" +
    "\031\051\001\002\000\060\004\uffcb\013\uffcb\015\uffcb\020" +
    "\uffcb\023\uffcb\024\uffcb\025\uffcb\027\uffcb\030\uffcb\031\uffcb" +
    "\032\uffcb\033\uffcb\034\uffcb\035\uffcb\036\uffcb\037\uffcb\040" +
    "\uffcb\041\uffcb\042\uffcb\045\uffcb\046\uffcb\050\uffcb\051\uffcb" +
    "\001\002\000\022\004\050\006\047\007\046\010\043\011" +
    "\042\012\045\026\040\031\051\001\002\000\042\013\104" +
    "\023\057\024\060\025\055\027\065\030\072\031\063\032" +
    "\067\033\054\034\053\036\071\037\070\040\066\041\062" +
    "\042\056\051\064\001\002\000\062\004\ufff9\013\ufff9\015" +
    "\ufff9\020\ufff9\021\ufff9\023\ufff9\024\ufff9\025\ufff9\027\ufff9" +
    "\030\ufff9\031\ufff9\032\ufff9\033\ufff9\034\ufff9\035\ufff9\036" +
    "\ufff9\037\ufff9\040\ufff9\041\ufff9\042\ufff9\045\ufff9\046\ufff9" +
    "\050\ufff9\051\ufff9\001\002\000\062\004\ufff7\013\ufff7\015" +
    "\ufff7\020\ufff7\021\ufff7\023\ufff7\024\ufff7\025\ufff7\027\ufff7" +
    "\030\ufff7\031\ufff7\032\ufff7\033\ufff7\034\ufff7\035\ufff7\036" +
    "\ufff7\037\ufff7\040\ufff7\041\ufff7\042\ufff7\045\ufff7\046\ufff7" +
    "\050\ufff7\051\ufff7\001\002\000\062\004\ufff4\013\ufff4\015" +
    "\ufff4\020\ufff4\021\ufff4\023\ufff4\024\ufff4\025\ufff4\027\ufff4" +
    "\030\ufff4\031\ufff4\032\ufff4\033\ufff4\034\ufff4\035\ufff4\036" +
    "\ufff4\037\ufff4\040\ufff4\041\ufff4\042\ufff4\045\ufff4\046\ufff4" +
    "\050\ufff4\051\ufff4\001\002\000\022\004\050\006\047\007" +
    "\046\010\043\011\042\012\045\026\040\031\051\001\002" +
    "\000\062\004\ufff6\013\ufff6\015\ufff6\020\ufff6\021\ufff6\023" +
    "\ufff6\024\ufff6\025\ufff6\027\ufff6\030\ufff6\031\ufff6\032\ufff6" +
    "\033\ufff6\034\ufff6\035\ufff6\036\ufff6\037\ufff6\040\ufff6\041" +
    "\ufff6\042\ufff6\045\ufff6\046\ufff6\050\ufff6\051\ufff6\001\002" +
    "\000\062\004\ufff8\013\ufff8\015\ufff8\020\ufff8\021\ufff8\023" +
    "\ufff8\024\ufff8\025\ufff8\027\ufff8\030\ufff8\031\ufff8\032\ufff8" +
    "\033\ufff8\034\ufff8\035\ufff8\036\ufff8\037\ufff8\040\ufff8\041" +
    "\ufff8\042\ufff8\045\ufff8\046\ufff8\050\ufff8\051\ufff8\001\002" +
    "\000\064\004\ufff5\012\074\013\ufff5\015\ufff5\020\ufff5\021" +
    "\ufff5\023\ufff5\024\ufff5\025\ufff5\027\ufff5\030\ufff5\031\ufff5" +
    "\032\ufff5\033\ufff5\034\ufff5\035\ufff5\036\ufff5\037\ufff5\040" +
    "\ufff5\041\ufff5\042\ufff5\045\ufff5\046\ufff5\050\ufff5\051\ufff5" +
    "\001\002\000\022\004\050\006\047\007\046\010\043\011" +
    "\042\012\045\026\040\031\051\001\002\000\060\004\uffc9" +
    "\013\uffc9\015\uffc9\020\uffc9\023\uffc9\024\uffc9\025\uffc9\027" +
    "\065\030\uffc9\031\uffc9\032\uffc9\033\uffc9\034\053\035\uffc9" +
    "\036\uffc9\037\uffc9\040\uffc9\041\uffc9\042\056\045\uffc9\046" +
    "\uffc9\050\uffc9\051\064\001\002\000\022\004\uffd4\006\uffd4" +
    "\007\uffd4\010\uffd4\011\uffd4\012\uffd4\026\uffd4\031\uffd4\001" +
    "\002\000\022\004\uffda\006\uffda\007\uffda\010\uffda\011\uffda" +
    "\012\uffda\026\uffda\031\uffda\001\002\000\022\004\uffdc\006" +
    "\uffdc\007\uffdc\010\uffdc\011\uffdc\012\uffdc\026\uffdc\031\uffdc" +
    "\001\002\000\022\004\uffd5\006\uffd5\007\uffd5\010\uffd5\011" +
    "\uffd5\012\uffd5\026\uffd5\031\uffd5\001\002\000\022\004\uffde" +
    "\006\uffde\007\uffde\010\uffde\011\uffde\012\uffde\026\uffde\031" +
    "\uffde\001\002\000\022\004\uffdd\006\uffdd\007\uffdd\010\uffdd" +
    "\011\uffdd\012\uffdd\026\uffdd\031\uffdd\001\002\000\022\004" +
    "\050\006\047\007\046\010\043\011\042\012\045\026\040" +
    "\031\051\001\002\000\022\004\uffdf\006\uffdf\007\uffdf\010" +
    "\uffdf\011\uffdf\012\uffdf\026\uffdf\031\uffdf\001\002\000\022" +
    "\004\uffd7\006\uffd7\007\uffd7\010\uffd7\011\uffd7\012\uffd7\026" +
    "\uffd7\031\uffd7\001\002\000\022\004\uffd6\006\uffd6\007\uffd6" +
    "\010\uffd6\011\uffd6\012\uffd6\026\uffd6\031\uffd6\001\002\000" +
    "\022\004\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012\uffd9" +
    "\026\uffd9\031\uffd9\001\002\000\022\004\uffe0\006\uffe0\007" +
    "\uffe0\010\uffe0\011\uffe0\012\uffe0\026\uffe0\031\uffe0\001\002" +
    "\000\022\004\uffdb\006\uffdb\007\uffdb\010\uffdb\011\uffdb\012" +
    "\uffdb\026\uffdb\031\uffdb\001\002\000\022\004\uffe1\006\uffe1" +
    "\007\uffe1\010\uffe1\011\uffe1\012\uffe1\026\uffe1\031\uffe1\001" +
    "\002\000\022\004\uffe2\006\uffe2\007\uffe2\010\uffe2\011\uffe2" +
    "\012\uffe2\026\uffe2\031\uffe2\001\002\000\022\004\uffd8\006" +
    "\uffd8\007\uffd8\010\uffd8\011\uffd8\012\uffd8\026\uffd8\031\uffd8" +
    "\001\002\000\060\004\uffcd\013\uffcd\015\uffcd\020\uffcd\023" +
    "\057\024\060\025\055\027\065\030\072\031\063\032\067" +
    "\033\054\034\053\035\uffcd\036\071\037\070\040\066\041" +
    "\062\042\056\045\uffcd\046\uffcd\050\uffcd\051\064\001\002" +
    "\000\014\004\050\006\047\007\046\010\043\011\042\001" +
    "\002\000\006\013\ufff2\021\ufff2\001\002\000\006\013\100" +
    "\021\077\001\002\000\014\004\050\006\047\007\046\010" +
    "\043\011\042\001\002\000\062\004\uffc8\013\uffc8\015\uffc8" +
    "\020\uffc8\021\uffc8\023\uffc8\024\uffc8\025\uffc8\027\uffc8\030" +
    "\uffc8\031\uffc8\032\uffc8\033\uffc8\034\uffc8\035\uffc8\036\uffc8" +
    "\037\uffc8\040\uffc8\041\uffc8\042\uffc8\045\uffc8\046\uffc8\050" +
    "\uffc8\051\uffc8\001\002\000\006\013\ufff3\021\ufff3\001\002" +
    "\000\042\013\103\023\057\024\060\025\055\027\065\030" +
    "\072\031\063\032\067\033\054\034\053\036\071\037\070" +
    "\040\066\041\062\042\056\051\064\001\002\000\060\004" +
    "\uffcc\013\uffcc\015\uffcc\020\uffcc\023\uffcc\024\uffcc\025\uffcc" +
    "\027\uffcc\030\uffcc\031\uffcc\032\uffcc\033\uffcc\034\uffcc\035" +
    "\uffcc\036\uffcc\037\uffcc\040\uffcc\041\uffcc\042\uffcc\045\uffcc" +
    "\046\uffcc\050\uffcc\051\uffcc\001\002\000\014\004\033\014" +
    "\107\035\035\046\032\050\025\001\002\000\016\004\uffd2" +
    "\015\uffd2\035\uffd2\045\113\046\uffd2\050\uffd2\001\002\000" +
    "\016\004\uffd1\015\uffd1\035\uffd1\045\uffd1\046\uffd1\050\uffd1" +
    "\001\002\000\012\004\033\035\035\046\032\050\025\001" +
    "\002\000\014\004\033\015\111\035\035\046\032\050\025" +
    "\001\002\000\016\004\uffd0\015\uffd0\035\uffd0\045\uffd0\046" +
    "\uffd0\050\uffd0\001\002\000\014\004\uffeb\015\uffeb\035\uffeb" +
    "\046\uffeb\050\uffeb\001\002\000\014\004\033\014\107\035" +
    "\035\046\032\050\025\001\002\000\016\004\uffd3\015\uffd3" +
    "\035\uffd3\045\uffd3\046\uffd3\050\uffd3\001\002\000\060\004" +
    "\uffca\013\uffca\015\uffca\020\uffca\023\uffca\024\uffca\025\uffca" +
    "\027\uffca\030\uffca\031\uffca\032\uffca\033\uffca\034\uffca\035" +
    "\uffca\036\uffca\037\uffca\040\uffca\041\uffca\042\uffca\045\uffca" +
    "\046\uffca\050\uffca\051\uffca\001\002\000\022\004\050\006" +
    "\047\007\046\010\043\011\042\012\045\026\040\031\051" +
    "\001\002\000\056\004\uffce\015\uffce\020\uffce\023\057\024" +
    "\060\025\055\027\065\030\072\031\063\032\067\033\054" +
    "\034\053\035\uffce\036\071\037\070\040\066\041\062\042" +
    "\056\045\uffce\046\uffce\050\uffce\051\064\001\002\000\022" +
    "\004\050\006\047\007\046\010\043\011\042\012\045\026" +
    "\040\031\051\001\002\000\042\013\122\023\057\024\060" +
    "\025\055\027\065\030\072\031\063\032\067\033\054\034" +
    "\053\036\071\037\070\040\066\041\062\042\056\051\064" +
    "\001\002\000\004\014\123\001\002\000\012\004\033\035" +
    "\035\046\032\050\025\001\002\000\014\004\033\015\125" +
    "\035\035\046\032\050\025\001\002\000\016\004\uffcf\015" +
    "\uffcf\035\uffcf\045\uffcf\046\uffcf\050\uffcf\001\002\000\010" +
    "\002\uffec\004\uffec\052\uffec\001\002\000\016\004\uffe4\015" +
    "\uffe4\035\uffe4\045\uffe4\046\uffe4\050\uffe4\001\002\000\056" +
    "\004\uffe5\015\uffe5\020\131\023\057\024\060\025\055\027" +
    "\065\030\072\031\063\032\067\033\054\034\053\035\uffe5" +
    "\036\071\037\070\040\066\041\062\042\056\045\uffe5\046" +
    "\uffe5\050\uffe5\051\064\001\002\000\016\004\uffe3\015\uffe3" +
    "\035\uffe3\045\uffe3\046\uffe3\050\uffe3\001\002\000\010\013" +
    "\ufffe\014\ufffe\021\ufffe\001\002\000\004\043\135\001\002" +
    "\000\004\014\ufff1\001\002\000\012\013\ufffd\014\ufffd\016" +
    "\136\021\ufffd\001\002\000\004\017\137\001\002\000\004" +
    "\016\140\001\002\000\004\017\141\001\002\000\010\013" +
    "\uffff\014\uffff\021\uffff\001\002\000\006\013\145\021\144" +
    "\001\002\000\006\013\uffed\021\uffed\001\002\000\004\043" +
    "\135\001\002\000\004\014\ufff0\001\002\000\006\013\uffee" +
    "\021\uffee\001\002\000\006\013\ufffb\021\ufffb\001\002\000" +
    "\004\043\135\001\002\000\006\013\ufffc\021\ufffc\001\002" +
    "\000\004\002\001\001\002\000\010\002\000\004\000\052" +
    "\000\001\002\000\010\002\uffc6\004\uffc6\052\uffc6\001\002" +
    "" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() {return _action_table;}

  /** {@code reduce_goto} table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\152\000\014\002\010\003\003\013\006\017\004\020" +
    "\007\001\001\000\002\001\001\000\010\003\003\013\006" +
    "\020\153\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\006\013\007\015\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\146\001\001\000\004" +
    "\012\021\001\001\000\006\004\131\005\133\001\001\000" +
    "\002\001\001\000\016\014\027\015\030\016\026\022\025" +
    "\023\033\024\023\001\001\000\002\001\001\000\010\010" +
    "\036\016\043\026\127\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\015\111\016\026\022\025\023\033\024" +
    "\023\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\010" +
    "\036\016\043\026\040\001\001\000\002\001\001\000\010" +
    "\010\036\016\043\026\114\001\001\000\004\025\060\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\010\036\016\043\026\101\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\010\036" +
    "\016\043\026\051\001\001\000\004\025\060\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\010" +
    "\036\016\043\026\072\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\025\060\001\001\000\010\010" +
    "\074\011\075\016\043\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\010\100\016\043\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\025\060\001\001\000\002" +
    "\001\001\000\016\015\105\016\026\022\025\023\033\024" +
    "\023\027\104\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\014\107\015\030\016\026\022\025\023\033\024" +
    "\023\001\001\000\014\015\111\016\026\022\025\023\033" +
    "\024\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\015\105\016\026\022\025\023\033\024\023\027\113" +
    "\001\001\000\002\001\001\000\004\025\060\001\001\000" +
    "\010\010\036\016\043\026\116\001\001\000\004\025\060" +
    "\001\001\000\010\010\036\016\043\026\120\001\001\000" +
    "\004\025\060\001\001\000\002\001\001\000\016\014\123" +
    "\015\030\016\026\022\025\023\033\024\023\001\001\000" +
    "\014\015\111\016\026\022\025\023\033\024\023\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\025\060\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\004\131\005\142\021\141\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\131\005\145\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\004" +
    "\131\005\150\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to {@code reduce_goto} table. */
  @Override
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack<java_cup.runtime.Symbol> stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 0;}

  /** {@code EOF} Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** {@code error} Symbol index. */
  @Override
  public int error_sym() {return 1;}



    // Connect this parser to a scanner!
    //Lexer s;
    CodeWriterSExpPrinter printer;
    parser(CodeWriterSExpPrinter printer){ this.printer=printer; }


/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
    private final parser parser;

    /** Constructor */
    CUP$parser$actions(parser parser) {
        this.parser = parser;
    }

    /** Method with the actual generated action code for actions 0 to 62. */
    public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            /* Symbol object for return from actions */
            java_cup.runtime.Symbol CUP$parser$result;

        /* select the action based on the action number */
        switch (CUP$parser$act_num) {
        /*. . . . . . . . . . . . . . . . . . . .*/
        case 0: // $START ::= program EOF 
            {
                Object RESULT = null;
                int start_valleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int start_valright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Object start_val = CUP$parser$stack.elementAt(CUP$parser$top-1).<Object> value();
                RESULT = start_val;
                CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            /* ACCEPT */
            CUP$parser$parser.done_parsing();
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 1: // useSpecifier ::= USE IDENTIFIER 
            {
                Object RESULT = null;
                 printer.printAtom("use"); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("useSpecifier",1, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 2: // array ::= INT LBRACK RBRACK LBRACK RBRACK 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("array",2, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 3: // type ::= array 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",3, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 4: // type ::= INT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",3, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 5: // argumentWithType ::= IDENTIFIER COLON type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentWithType",4, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 6: // argumentsWithType ::= argumentsWithType COMMA argumentWithType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",5, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 7: // argumentsWithType ::= argumentWithType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",5, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 8: // argument ::= BOOLEAN_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 9: // argument ::= INTEGER_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 10: // argument ::= CHARACTER_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 11: // argument ::= STRING_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 12: // argument ::= IDENTIFIER 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 13: // argument ::= functionCall 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 14: // arguments ::= arguments COMMA argument 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("arguments",7, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 15: // arguments ::= argument 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("arguments",7, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 16: // functionReturnType ::= COLON type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 17: // functionReturnType ::= COLON LPAREN typesList RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 18: // functionReturnType ::= 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 19: // typesList ::= typesList COMMA type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",15, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 20: // typesList ::= type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",15, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 21: // function ::= IDENTIFIER LPAREN argumentsWithType RPAREN functionReturnType LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;
                 printer.printAtom("Function"); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("function",9, CUP$parser$stack.elementAt(CUP$parser$top-7), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 22: // multipleStatements ::= multipleStatements statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("multipleStatements",10, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 23: // multipleStatements ::= statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("multipleStatements",10, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 24: // statement ::= functionCall 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 25: // statement ::= assignment 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 26: // statement ::= ifStatement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 27: // statement ::= whileStatement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 28: // statement ::= RETURN expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 29: // statement ::= assignment SEMICOLON 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 30: // statement ::= RETURN expression SEMICOLON 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 31: // operator ::= EQEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 32: // operator ::= GTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 33: // operator ::= LTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 34: // operator ::= NOTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 35: // operator ::= EQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 36: // operator ::= GT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 37: // operator ::= LT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 38: // operator ::= AND 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 39: // operator ::= OR 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 40: // operator ::= MULT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 41: // operator ::= PLUS 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 42: // operator ::= MINUS 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 43: // operator ::= DIV 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 44: // operator ::= HIGHMULT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 45: // operator ::= MOD 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 46: // ifStatement ::= IF LPAREN expression RPAREN oneOrMorestatements ELSE oneOrMorestatements 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("ifStatement",17, CUP$parser$stack.elementAt(CUP$parser$top-6), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 47: // ifStatement ::= IF LPAREN expression RPAREN oneOrMorestatements 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("ifStatement",17, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 48: // oneOrMorestatements ::= statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("oneOrMorestatements",21, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 49: // oneOrMorestatements ::= LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("oneOrMorestatements",21, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 50: // whileStatement ::= WHILE LPAREN expression RPAREN LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("whileStatement",18, CUP$parser$stack.elementAt(CUP$parser$top-6), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 51: // assignment ::= IDENTIFIER EQ expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",16, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 52: // expression ::= expression operator expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 53: // expression ::= LPAREN expression RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 54: // expression ::= argument 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 55: // expression ::= NOT expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 56: // expression ::= MINUS expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 57: // functionCall ::= IDENTIFIER LPAREN arguments RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionCall",12, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 58: // program ::= blocks 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 59: // blocks ::= blocks block 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("blocks",13, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 60: // blocks ::= block 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("blocks",13, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 61: // block ::= useSpecifier 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("block",14, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 62: // block ::= function 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("block",14, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /* . . . . . .*/
        default:
            throw new Exception(
                  "Invalid action number " + CUP$parser$act_num + " found in internal parse table");

        }
    } /* end of method */

    /** Method splitting the generated action code into several parts. */
    public final java_cup.runtime.Symbol CUP$parser$do_action(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            return CUP$parser$do_action_part00000000(
                           CUP$parser$act_num,
                           CUP$parser$parser,
                           CUP$parser$stack,
                           CUP$parser$top);
    }
}

}
