
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package zr54.parser;

import zr54.lexer.*;
import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*;

/** CUP v0.11b 20150326 generated parser.
  */
public class parser
 extends java_cup.runtime.lr_parser {

  @Override
  public final Class<?> getSymbolContainer() {
    return sym.class;
  }

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner and a SymbolFactory. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\104\000\002\002\004\000\002\003\004\000\002\004" +
    "\004\000\002\004\004\000\002\030\005\000\002\030\004" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\006\005\000\002\007\005\000\002\007\003\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\011\005" +
    "\000\002\011\003\000\002\012\004\000\002\012\006\000" +
    "\002\012\002\000\002\021\005\000\002\021\003\000\002" +
    "\013\012\000\002\014\004\000\002\014\003\000\002\015" +
    "\003\000\002\015\003\000\002\015\003\000\002\015\003" +
    "\000\002\015\004\000\002\015\004\000\002\015\005\000" +
    "\002\025\003\000\002\025\003\000\002\025\003\000\002" +
    "\025\003\000\002\025\003\000\002\025\003\000\002\025" +
    "\003\000\002\025\003\000\002\025\003\000\002\025\003" +
    "\000\002\025\003\000\002\025\003\000\002\025\003\000" +
    "\002\025\003\000\002\025\003\000\002\023\011\000\002" +
    "\023\007\000\002\027\003\000\002\027\005\000\002\024" +
    "\011\000\002\022\005\000\002\026\005\000\002\026\005" +
    "\000\002\026\003\000\002\026\004\000\002\026\004\000" +
    "\002\016\006\000\002\016\006\000\002\002\003\000\002" +
    "\017\004\000\002\017\003\000\002\020\003\000\002\020" +
    "\003" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\006\004\012\051\006\001\002\000\010\002" +
    "\uffbf\004\uffbf\051\uffbf\001\002\000\010\002\uffc2\004\012" +
    "\051\006\001\002\000\004\004\162\001\002\000\010\002" +
    "\uffbe\004\uffbe\051\uffbe\001\002\000\010\002\uffc0\004\uffc0" +
    "\051\uffc0\001\002\000\004\002\161\001\002\000\004\011" +
    "\013\001\002\000\004\004\015\001\002\000\006\012\ufff6" +
    "\020\ufff6\001\002\000\004\021\157\001\002\000\006\012" +
    "\020\020\017\001\002\000\004\004\015\001\002\000\006" +
    "\013\uffeb\021\021\001\002\000\010\011\140\042\142\043" +
    "\137\001\002\000\004\013\023\001\002\000\014\004\034" +
    "\034\036\045\033\046\027\047\025\001\002\000\020\004" +
    "\uffe2\014\uffe2\034\uffe2\044\uffe2\045\uffe2\046\uffe2\047\uffe2" +
    "\001\002\000\024\004\051\005\050\006\047\007\044\010" +
    "\043\011\046\025\041\030\052\046\027\001\002\000\022" +
    "\004\uffe4\014\uffe4\017\133\034\uffe4\044\uffe4\045\uffe4\046" +
    "\uffe4\047\uffe4\001\002\000\004\011\130\001\002\000\020" +
    "\004\uffe5\014\uffe5\034\uffe5\044\uffe5\045\uffe5\046\uffe5\047" +
    "\uffe5\001\002\000\016\004\034\014\127\034\036\045\033" +
    "\046\027\047\025\001\002\000\016\004\uffe6\014\uffe6\034" +
    "\uffe6\045\uffe6\046\uffe6\047\uffe6\001\002\000\004\011\121" +
    "\001\002\000\006\011\075\022\117\001\002\000\020\004" +
    "\uffe3\014\uffe3\034\uffe3\044\uffe3\045\uffe3\046\uffe3\047\uffe3" +
    "\001\002\000\004\011\037\001\002\000\024\004\051\005" +
    "\050\006\047\007\044\010\043\011\046\025\041\030\052" +
    "\046\027\001\002\000\062\004\uffc7\012\uffc7\014\uffc7\017" +
    "\uffc7\022\uffc7\023\uffc7\024\uffc7\026\uffc7\027\uffc7\030\uffc7" +
    "\031\uffc7\032\uffc7\033\uffc7\034\uffc7\035\uffc7\036\uffc7\037" +
    "\uffc7\040\uffc7\041\uffc7\044\uffc7\045\uffc7\046\uffc7\047\uffc7" +
    "\050\uffc7\001\002\000\024\004\051\005\050\006\047\007" +
    "\044\010\043\011\046\025\041\030\052\046\027\001\002" +
    "\000\042\012\105\022\060\023\061\024\056\026\066\027" +
    "\073\030\064\031\070\032\054\033\055\035\072\036\071" +
    "\037\067\040\063\041\057\050\065\001\002\000\064\004" +
    "\ufff5\012\ufff5\014\ufff5\017\ufff5\020\ufff5\022\ufff5\023\ufff5" +
    "\024\ufff5\026\ufff5\027\ufff5\030\ufff5\031\ufff5\032\ufff5\033" +
    "\ufff5\034\ufff5\035\ufff5\036\ufff5\037\ufff5\040\ufff5\041\ufff5" +
    "\044\ufff5\045\ufff5\046\ufff5\047\ufff5\050\ufff5\001\002\000" +
    "\064\004\ufff3\012\ufff3\014\ufff3\017\ufff3\020\ufff3\022\ufff3" +
    "\023\ufff3\024\ufff3\026\ufff3\027\ufff3\030\ufff3\031\ufff3\032" +
    "\ufff3\033\ufff3\034\ufff3\035\ufff3\036\ufff3\037\ufff3\040\ufff3" +
    "\041\ufff3\044\ufff3\045\ufff3\046\ufff3\047\ufff3\050\ufff3\001" +
    "\002\000\064\004\ufff0\012\ufff0\014\ufff0\017\ufff0\020\ufff0" +
    "\022\ufff0\023\ufff0\024\ufff0\026\ufff0\027\ufff0\030\ufff0\031" +
    "\ufff0\032\ufff0\033\ufff0\034\ufff0\035\ufff0\036\ufff0\037\ufff0" +
    "\040\ufff0\041\ufff0\044\ufff0\045\ufff0\046\ufff0\047\ufff0\050" +
    "\ufff0\001\002\000\024\004\051\005\050\006\047\007\044" +
    "\010\043\011\046\025\041\030\052\046\027\001\002\000" +
    "\064\004\ufff2\012\ufff2\014\ufff2\017\ufff2\020\ufff2\022\ufff2" +
    "\023\ufff2\024\ufff2\026\ufff2\027\ufff2\030\ufff2\031\ufff2\032" +
    "\ufff2\033\ufff2\034\ufff2\035\ufff2\036\ufff2\037\ufff2\040\ufff2" +
    "\041\ufff2\044\ufff2\045\ufff2\046\ufff2\047\ufff2\050\ufff2\001" +
    "\002\000\064\004\ufff4\012\ufff4\014\ufff4\017\ufff4\020\ufff4" +
    "\022\ufff4\023\ufff4\024\ufff4\026\ufff4\027\ufff4\030\ufff4\031" +
    "\ufff4\032\ufff4\033\ufff4\034\ufff4\035\ufff4\036\ufff4\037\ufff4" +
    "\040\ufff4\041\ufff4\044\ufff4\045\ufff4\046\ufff4\047\ufff4\050" +
    "\ufff4\001\002\000\066\004\ufff1\011\075\012\ufff1\014\ufff1" +
    "\017\ufff1\020\ufff1\022\ufff1\023\ufff1\024\ufff1\026\ufff1\027" +
    "\ufff1\030\ufff1\031\ufff1\032\ufff1\033\ufff1\034\ufff1\035\ufff1" +
    "\036\ufff1\037\ufff1\040\ufff1\041\ufff1\044\ufff1\045\ufff1\046" +
    "\ufff1\047\ufff1\050\ufff1\001\002\000\024\004\051\005\050" +
    "\006\047\007\044\010\043\011\046\025\041\030\052\046" +
    "\027\001\002\000\062\004\uffc5\012\uffc5\014\uffc5\017\uffc5" +
    "\022\uffc5\023\uffc5\024\uffc5\026\066\027\uffc5\030\uffc5\031" +
    "\uffc5\032\uffc5\033\055\034\uffc5\035\uffc5\036\uffc5\037\uffc5" +
    "\040\uffc5\041\057\044\uffc5\045\uffc5\046\uffc5\047\uffc5\050" +
    "\065\001\002\000\024\004\uffd6\005\uffd6\006\uffd6\007\uffd6" +
    "\010\uffd6\011\uffd6\025\uffd6\030\uffd6\046\uffd6\001\002\000" +
    "\024\004\uffd0\005\uffd0\006\uffd0\007\uffd0\010\uffd0\011\uffd0" +
    "\025\uffd0\030\uffd0\046\uffd0\001\002\000\024\004\uffd8\005" +
    "\uffd8\006\uffd8\007\uffd8\010\uffd8\011\uffd8\025\uffd8\030\uffd8" +
    "\046\uffd8\001\002\000\024\004\uffd1\005\uffd1\006\uffd1\007" +
    "\uffd1\010\uffd1\011\uffd1\025\uffd1\030\uffd1\046\uffd1\001\002" +
    "\000\024\004\uffda\005\uffda\006\uffda\007\uffda\010\uffda\011" +
    "\uffda\025\uffda\030\uffda\046\uffda\001\002\000\024\004\uffd9" +
    "\005\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\025\uffd9\030" +
    "\uffd9\046\uffd9\001\002\000\024\004\051\005\050\006\047" +
    "\007\044\010\043\011\046\025\041\030\052\046\027\001" +
    "\002\000\024\004\uffdb\005\uffdb\006\uffdb\007\uffdb\010\uffdb" +
    "\011\uffdb\025\uffdb\030\uffdb\046\uffdb\001\002\000\024\004" +
    "\uffd3\005\uffd3\006\uffd3\007\uffd3\010\uffd3\011\uffd3\025\uffd3" +
    "\030\uffd3\046\uffd3\001\002\000\024\004\uffd2\005\uffd2\006" +
    "\uffd2\007\uffd2\010\uffd2\011\uffd2\025\uffd2\030\uffd2\046\uffd2" +
    "\001\002\000\024\004\uffd5\005\uffd5\006\uffd5\007\uffd5\010" +
    "\uffd5\011\uffd5\025\uffd5\030\uffd5\046\uffd5\001\002\000\024" +
    "\004\uffdc\005\uffdc\006\uffdc\007\uffdc\010\uffdc\011\uffdc\025" +
    "\uffdc\030\uffdc\046\uffdc\001\002\000\024\004\uffd7\005\uffd7" +
    "\006\uffd7\007\uffd7\010\uffd7\011\uffd7\025\uffd7\030\uffd7\046" +
    "\uffd7\001\002\000\024\004\uffdd\005\uffdd\006\uffdd\007\uffdd" +
    "\010\uffdd\011\uffdd\025\uffdd\030\uffdd\046\uffdd\001\002\000" +
    "\024\004\uffde\005\uffde\006\uffde\007\uffde\010\uffde\011\uffde" +
    "\025\uffde\030\uffde\046\uffde\001\002\000\024\004\uffd4\005" +
    "\uffd4\006\uffd4\007\uffd4\010\uffd4\011\uffd4\025\uffd4\030\uffd4" +
    "\046\uffd4\001\002\000\062\004\uffc9\012\uffc9\014\uffc9\017" +
    "\uffc9\022\060\023\061\024\056\026\066\027\073\030\064" +
    "\031\070\032\054\033\055\034\uffc9\035\072\036\071\037" +
    "\067\040\063\041\057\044\uffc9\045\uffc9\046\uffc9\047\uffc9" +
    "\050\065\001\002\000\016\004\051\005\050\006\047\007" +
    "\044\010\043\046\027\001\002\000\006\012\uffee\020\uffee" +
    "\001\002\000\006\012\101\020\100\001\002\000\016\004" +
    "\051\005\050\006\047\007\044\010\043\046\027\001\002" +
    "\000\064\004\uffc4\012\uffc4\014\uffc4\017\uffc4\020\uffc4\022" +
    "\uffc4\023\uffc4\024\uffc4\026\uffc4\027\uffc4\030\uffc4\031\uffc4" +
    "\032\uffc4\033\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\040" +
    "\uffc4\041\uffc4\044\uffc4\045\uffc4\046\uffc4\047\uffc4\050\uffc4" +
    "\001\002\000\006\012\uffef\020\uffef\001\002\000\042\012" +
    "\104\022\060\023\061\024\056\026\066\027\073\030\064" +
    "\031\070\032\054\033\055\035\072\036\071\037\067\040" +
    "\063\041\057\050\065\001\002\000\062\004\uffc8\012\uffc8" +
    "\014\uffc8\017\uffc8\022\uffc8\023\uffc8\024\uffc8\026\uffc8\027" +
    "\uffc8\030\uffc8\031\uffc8\032\uffc8\033\uffc8\034\uffc8\035\uffc8" +
    "\036\uffc8\037\uffc8\040\uffc8\041\uffc8\044\uffc8\045\uffc8\046" +
    "\uffc8\047\uffc8\050\uffc8\001\002\000\016\004\034\013\110" +
    "\034\036\045\033\046\027\047\025\001\002\000\020\004" +
    "\uffce\014\uffce\034\uffce\044\114\045\uffce\046\uffce\047\uffce" +
    "\001\002\000\020\004\uffcd\014\uffcd\034\uffcd\044\uffcd\045" +
    "\uffcd\046\uffcd\047\uffcd\001\002\000\014\004\034\034\036" +
    "\045\033\046\027\047\025\001\002\000\016\004\034\014" +
    "\112\034\036\045\033\046\027\047\025\001\002\000\020" +
    "\004\uffcc\014\uffcc\034\uffcc\044\uffcc\045\uffcc\046\uffcc\047" +
    "\uffcc\001\002\000\016\004\uffe7\014\uffe7\034\uffe7\045\uffe7" +
    "\046\uffe7\047\uffe7\001\002\000\016\004\034\013\110\034" +
    "\036\045\033\046\027\047\025\001\002\000\020\004\uffcf" +
    "\014\uffcf\034\uffcf\044\uffcf\045\uffcf\046\uffcf\047\uffcf\001" +
    "\002\000\062\004\uffc6\012\uffc6\014\uffc6\017\uffc6\022\uffc6" +
    "\023\uffc6\024\uffc6\026\uffc6\027\uffc6\030\uffc6\031\uffc6\032" +
    "\uffc6\033\uffc6\034\uffc6\035\uffc6\036\uffc6\037\uffc6\040\uffc6" +
    "\041\uffc6\044\uffc6\045\uffc6\046\uffc6\047\uffc6\050\uffc6\001" +
    "\002\000\024\004\051\005\050\006\047\007\044\010\043" +
    "\011\046\025\041\030\052\046\027\001\002\000\060\004" +
    "\uffca\014\uffca\017\uffca\022\060\023\061\024\056\026\066" +
    "\027\073\030\064\031\070\032\054\033\055\034\uffca\035" +
    "\072\036\071\037\067\040\063\041\057\044\uffca\045\uffca" +
    "\046\uffca\047\uffca\050\065\001\002\000\024\004\051\005" +
    "\050\006\047\007\044\010\043\011\046\025\041\030\052" +
    "\046\027\001\002\000\042\012\123\022\060\023\061\024" +
    "\056\026\066\027\073\030\064\031\070\032\054\033\055" +
    "\035\072\036\071\037\067\040\063\041\057\050\065\001" +
    "\002\000\004\013\124\001\002\000\014\004\034\034\036" +
    "\045\033\046\027\047\025\001\002\000\016\004\034\014" +
    "\126\034\036\045\033\046\027\047\025\001\002\000\020" +
    "\004\uffcb\014\uffcb\034\uffcb\044\uffcb\045\uffcb\046\uffcb\047" +
    "\uffcb\001\002\000\010\002\uffe8\004\uffe8\051\uffe8\001\002" +
    "\000\004\004\131\001\002\000\004\012\132\001\002\000" +
    "\064\004\uffc3\012\uffc3\014\uffc3\017\uffc3\020\uffc3\022\uffc3" +
    "\023\uffc3\024\uffc3\026\uffc3\027\uffc3\030\uffc3\031\uffc3\032" +
    "\uffc3\033\uffc3\034\uffc3\035\uffc3\036\uffc3\037\uffc3\040\uffc3" +
    "\041\uffc3\044\uffc3\045\uffc3\046\uffc3\047\uffc3\050\uffc3\001" +
    "\002\000\020\004\uffe0\014\uffe0\034\uffe0\044\uffe0\045\uffe0" +
    "\046\uffe0\047\uffe0\001\002\000\060\004\uffe1\014\uffe1\017" +
    "\135\022\060\023\061\024\056\026\066\027\073\030\064" +
    "\031\070\032\054\033\055\034\uffe1\035\072\036\071\037" +
    "\067\040\063\041\057\044\uffe1\045\uffe1\046\uffe1\047\uffe1" +
    "\050\065\001\002\000\020\004\uffdf\014\uffdf\034\uffdf\044" +
    "\uffdf\045\uffdf\046\uffdf\047\uffdf\001\002\000\010\012\ufffb" +
    "\013\ufffb\020\ufffb\001\002\000\012\012\ufff9\013\ufff9\015" +
    "\143\020\ufff9\001\002\000\006\042\142\043\137\001\002" +
    "\000\004\013\uffed\001\002\000\012\012\ufffa\013\ufffa\015" +
    "\143\020\ufffa\001\002\000\004\016\147\001\002\000\012" +
    "\012\uffff\013\uffff\015\145\020\uffff\001\002\000\004\016" +
    "\146\001\002\000\012\012\ufffd\013\ufffd\015\ufffd\020\ufffd" +
    "\001\002\000\012\012\ufffc\013\ufffc\015\ufffc\020\ufffc\001" +
    "\002\000\006\012\153\020\152\001\002\000\006\012\uffe9" +
    "\020\uffe9\001\002\000\006\042\142\043\137\001\002\000" +
    "\004\013\uffec\001\002\000\006\012\uffea\020\uffea\001\002" +
    "\000\012\012\ufffe\013\ufffe\015\145\020\ufffe\001\002\000" +
    "\006\012\ufff7\020\ufff7\001\002\000\006\042\142\043\137" +
    "\001\002\000\006\012\ufff8\020\ufff8\001\002\000\004\002" +
    "\001\001\002\000\010\002\000\004\000\051\000\001\002" +
    "\000\010\002\uffc1\004\uffc1\051\uffc1\001\002" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() {return _action_table;}

  /** {@code reduce_goto} table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\014\002\010\003\003\013\006\017\004\020" +
    "\007\001\001\000\002\001\001\000\010\003\003\013\006" +
    "\020\162\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\006\013\007\015\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\155\001\001\000\004" +
    "\012\021\001\001\000\006\004\135\005\140\001\001\000" +
    "\002\001\001\000\016\014\030\015\031\016\027\022\025" +
    "\023\034\024\023\001\001\000\002\001\001\000\010\010" +
    "\037\016\044\026\133\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\015\112\016\027\022" +
    "\025\023\034\024\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\010\037\016\044\026\041\001\001\000\002" +
    "\001\001\000\010\010\037\016\044\026\115\001\001\000" +
    "\004\025\061\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\010\037\016\044\026\102\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\010\037\016\044\026\052\001\001\000\004\025" +
    "\061\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\010\037\016\044\026\073\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\025\061\001" +
    "\001\000\010\010\075\011\076\016\044\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\010\101\016\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\025\061" +
    "\001\001\000\002\001\001\000\016\015\106\016\027\022" +
    "\025\023\034\024\023\027\105\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\014\110\015\031\016\027\022" +
    "\025\023\034\024\023\001\001\000\014\015\112\016\027" +
    "\022\025\023\034\024\023\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\015\106\016\027\022\025\023\034" +
    "\024\023\027\114\001\001\000\002\001\001\000\004\025" +
    "\061\001\001\000\010\010\037\016\044\026\117\001\001" +
    "\000\004\025\061\001\001\000\010\010\037\016\044\026" +
    "\121\001\001\000\004\025\061\001\001\000\002\001\001" +
    "\000\016\014\124\015\031\016\027\022\025\023\034\024" +
    "\023\001\001\000\014\015\112\016\027\022\025\023\034" +
    "\024\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\025\061\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\030\154\001\001\000\010\004\135" +
    "\005\150\021\147\001\001\000\002\001\001\000\004\030" +
    "\143\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\004\135\005\153\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\135\005\157\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to {@code reduce_goto} table. */
  @Override
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack<java_cup.runtime.Symbol> stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 0;}

  /** {@code EOF} Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** {@code error} Symbol index. */
  @Override
  public int error_sym() {return 1;}



    // Connect this parser to a scanner!
    //Lexer s;
    CodeWriterSExpPrinter printer;
    parser(CodeWriterSExpPrinter printer){ this.printer=printer; }


/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
    private final parser parser;

    /** Constructor */
    CUP$parser$actions(parser parser) {
        this.parser = parser;
    }

    /** Method with the actual generated action code for actions 0 to 67. */
    public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            /* Symbol object for return from actions */
            java_cup.runtime.Symbol CUP$parser$result;

        /* select the action based on the action number */
        switch (CUP$parser$act_num) {
        /*. . . . . . . . . . . . . . . . . . . .*/
        case 0: // $START ::= program EOF 
            {
                Object RESULT = null;
                int start_valleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int start_valright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Object start_val = CUP$parser$stack.elementAt(CUP$parser$top-1).<Object> value();
                RESULT = start_val;
                CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            /* ACCEPT */
            CUP$parser$parser.done_parsing();
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 1: // useSpecifier ::= USE IDENTIFIER 
            {
                Object RESULT = null;
                 printer.printAtom("use"); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("useSpecifier",1, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 2: // arrayType ::= INT brackets 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",2, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 3: // arrayType ::= BOOL brackets 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",2, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 4: // brackets ::= brackets LBRACK RBRACK 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",22, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 5: // brackets ::= LBRACK RBRACK 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",22, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 6: // type ::= arrayType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",3, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 7: // type ::= INT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",3, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 8: // type ::= BOOL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",3, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 9: // argumentWithType ::= IDENTIFIER COLON type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentWithType",4, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 10: // argumentsWithType ::= argumentsWithType COMMA argumentWithType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",5, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 11: // argumentsWithType ::= argumentWithType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",5, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 12: // argument ::= BOOLEAN_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 13: // argument ::= INTEGER_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 14: // argument ::= CHARACTER_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 15: // argument ::= STRING_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 16: // argument ::= IDENTIFIER 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 17: // argument ::= functionCall 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 18: // arguments ::= arguments COMMA argument 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("arguments",7, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 19: // arguments ::= argument 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("arguments",7, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 20: // functionReturnType ::= COLON type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 21: // functionReturnType ::= COLON LPAREN typesList RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 22: // functionReturnType ::= 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 23: // typesList ::= typesList COMMA type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",15, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 24: // typesList ::= type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",15, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 25: // function ::= IDENTIFIER LPAREN argumentsWithType RPAREN functionReturnType LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;
                 printer.printAtom("Function"); 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("function",9, CUP$parser$stack.elementAt(CUP$parser$top-7), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 26: // multipleStatements ::= multipleStatements statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("multipleStatements",10, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 27: // multipleStatements ::= statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("multipleStatements",10, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 28: // statement ::= functionCall 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 29: // statement ::= assignment 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 30: // statement ::= ifStatement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 31: // statement ::= whileStatement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 32: // statement ::= RETURN expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 33: // statement ::= assignment SEMICOLON 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 34: // statement ::= RETURN expression SEMICOLON 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",11, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 35: // operator ::= EQEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 36: // operator ::= GTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 37: // operator ::= LTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 38: // operator ::= NOTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 39: // operator ::= EQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 40: // operator ::= GT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 41: // operator ::= LT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 42: // operator ::= AND 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 43: // operator ::= OR 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 44: // operator ::= MULT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 45: // operator ::= PLUS 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 46: // operator ::= MINUS 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 47: // operator ::= DIV 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 48: // operator ::= HIGHMULT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 49: // operator ::= MOD 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",19, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 50: // ifStatement ::= IF LPAREN expression RPAREN oneOrMorestatements ELSE oneOrMorestatements 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("ifStatement",17, CUP$parser$stack.elementAt(CUP$parser$top-6), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 51: // ifStatement ::= IF LPAREN expression RPAREN oneOrMorestatements 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("ifStatement",17, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 52: // oneOrMorestatements ::= statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("oneOrMorestatements",21, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 53: // oneOrMorestatements ::= LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("oneOrMorestatements",21, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 54: // whileStatement ::= WHILE LPAREN expression RPAREN LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("whileStatement",18, CUP$parser$stack.elementAt(CUP$parser$top-6), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 55: // assignment ::= IDENTIFIER EQ expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",16, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 56: // expression ::= expression operator expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 57: // expression ::= LPAREN expression RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 58: // expression ::= argument 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 59: // expression ::= NOT expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 60: // expression ::= MINUS expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",20, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 61: // functionCall ::= IDENTIFIER LPAREN arguments RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionCall",12, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 62: // functionCall ::= LENGTH LPAREN IDENTIFIER RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionCall",12, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 63: // program ::= blocks 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 64: // blocks ::= blocks block 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("blocks",13, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 65: // blocks ::= block 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("blocks",13, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 66: // block ::= useSpecifier 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("block",14, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 67: // block ::= function 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("block",14, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /* . . . . . .*/
        default:
            throw new Exception(
                  "Invalid action number " + CUP$parser$act_num + " found in internal parse table");

        }
    } /* end of method */

    /** Method splitting the generated action code into several parts. */
    public final java_cup.runtime.Symbol CUP$parser$do_action(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            return CUP$parser$do_action_part00000000(
                           CUP$parser$act_num,
                           CUP$parser$parser,
                           CUP$parser$stack,
                           CUP$parser$top);
    }
}

}
