
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package zr54.parser;

import zr54.lexer.*;
import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*;

/** CUP v0.11b 20150326 generated parser.
  */
public class parser
 extends java_cup.runtime.lr_parser {

  @Override
  public final Class<?> getSymbolContainer() {
    return sym.class;
  }

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner and a SymbolFactory. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\116\000\002\002\004\000\002\003\004\000\002\005" +
    "\004\000\002\005\004\000\002\025\005\000\002\025\004" +
    "\000\002\025\006\000\002\025\005\000\002\006\003\000" +
    "\002\006\003\000\002\006\003\000\002\007\005\000\002" +
    "\010\005\000\002\010\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\003\000\002\012\004\000\002\012\006\000" +
    "\002\012\002\000\002\016\005\000\002\016\003\000\002" +
    "\032\012\000\002\013\004\000\002\013\003\000\002\014" +
    "\003\000\002\014\003\000\002\014\003\000\002\014\003" +
    "\000\002\014\006\000\002\014\004\000\002\014\007\000" +
    "\002\014\004\000\002\014\003\000\002\014\004\000\002" +
    "\022\003\000\002\022\003\000\002\022\003\000\002\022" +
    "\003\000\002\022\003\000\002\022\003\000\002\022\003" +
    "\000\002\022\003\000\002\022\003\000\002\022\003\000" +
    "\002\022\003\000\002\022\003\000\002\022\003\000\002" +
    "\022\003\000\002\020\011\000\002\020\007\000\002\024" +
    "\003\000\002\024\005\000\002\021\011\000\002\017\005" +
    "\000\002\017\011\000\002\026\005\000\002\026\003\000" +
    "\002\027\003\000\002\027\003\000\002\027\003\000\002" +
    "\023\005\000\002\023\005\000\002\023\003\000\002\023" +
    "\004\000\002\023\004\000\002\030\003\000\002\030\005" +
    "\000\002\015\006\000\002\015\006\000\002\002\004\000" +
    "\002\004\004\000\002\004\003\000\002\031\004\000\002" +
    "\031\003" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\202\000\004\051\005\001\002\000\006\004\uffb6\051" +
    "\uffb6\001\002\000\004\004\204\001\002\000\006\004\014" +
    "\051\005\001\002\000\004\002\010\001\002\000\004\002" +
    "\001\001\002\000\006\002\uffb4\004\uffb4\001\002\000\006" +
    "\004\uffb7\051\uffb7\001\002\000\006\002\uffb8\004\014\001" +
    "\002\000\004\011\015\001\002\000\004\004\017\001\002" +
    "\000\006\012\ufff4\020\ufff4\001\002\000\004\021\123\001" +
    "\002\000\006\012\022\020\021\001\002\000\004\004\017" +
    "\001\002\000\006\013\uffeb\021\023\001\002\000\010\011" +
    "\173\042\127\043\125\001\002\000\004\013\025\001\002" +
    "\000\016\004\042\034\043\045\041\046\030\047\033\052" +
    "\026\001\002\000\004\022\uffc4\001\002\000\024\004\uffe4" +
    "\014\uffe4\017\172\034\uffe4\044\uffe4\045\uffe4\046\uffe4\047" +
    "\uffe4\052\uffe4\001\002\000\004\011\167\001\002\000\022" +
    "\004\uffe3\014\uffe3\034\uffe3\044\uffe3\045\uffe3\046\uffe3\047" +
    "\uffe3\052\uffe3\001\002\000\022\004\uffe2\014\uffe2\034\uffe2" +
    "\044\uffe2\045\uffe2\046\uffe2\047\uffe2\052\uffe2\001\002\000" +
    "\004\011\163\001\002\000\026\004\uffdd\014\uffdd\017\162" +
    "\022\uffc2\034\uffdd\044\uffdd\045\uffdd\046\uffdd\047\uffdd\052" +
    "\uffdd\001\002\000\024\004\uffe5\014\uffe5\017\161\034\uffe5" +
    "\044\uffe5\045\uffe5\046\uffe5\047\uffe5\052\uffe5\001\002\000" +
    "\004\022\151\001\002\000\020\004\042\014\150\034\043" +
    "\045\041\046\030\047\033\052\026\001\002\000\020\004" +
    "\uffe6\014\uffe6\034\uffe6\045\uffe6\046\uffe6\047\uffe6\052\uffe6" +
    "\001\002\000\004\011\142\001\002\000\010\011\101\021" +
    "\123\022\uffc3\001\002\000\004\011\044\001\002\000\024" +
    "\004\056\005\054\006\055\007\050\010\051\011\053\025" +
    "\046\030\057\046\030\001\002\000\064\004\uffbf\012\uffbf" +
    "\014\uffbf\017\uffbf\020\uffbf\023\uffbf\024\uffbf\026\uffbf\027" +
    "\uffbf\030\uffbf\031\uffbf\032\uffbf\033\uffbf\034\uffbf\035\uffbf" +
    "\036\uffbf\037\uffbf\040\uffbf\041\uffbf\044\uffbf\045\uffbf\046" +
    "\uffbf\047\uffbf\050\uffbf\052\uffbf\001\002\000\024\004\056" +
    "\005\054\006\055\007\050\010\051\011\053\025\046\030" +
    "\057\046\030\001\002\000\040\012\111\023\065\024\063" +
    "\026\072\027\077\030\067\031\074\032\062\033\061\035" +
    "\075\036\076\037\073\040\070\041\064\050\071\001\002" +
    "\000\064\004\ufff1\012\ufff1\014\ufff1\017\ufff1\020\ufff1\023" +
    "\ufff1\024\ufff1\026\ufff1\027\ufff1\030\ufff1\031\ufff1\032\ufff1" +
    "\033\ufff1\034\ufff1\035\ufff1\036\ufff1\037\ufff1\040\ufff1\041" +
    "\ufff1\044\ufff1\045\ufff1\046\ufff1\047\ufff1\050\ufff1\052\ufff1" +
    "\001\002\000\064\004\ufff3\012\ufff3\014\ufff3\017\ufff3\020" +
    "\ufff3\023\ufff3\024\ufff3\026\ufff3\027\ufff3\030\ufff3\031\ufff3" +
    "\032\ufff3\033\ufff3\034\ufff3\035\ufff3\036\ufff3\037\ufff3\040" +
    "\ufff3\041\ufff3\044\ufff3\045\ufff3\046\ufff3\047\ufff3\050\ufff3" +
    "\052\ufff3\001\002\000\064\004\uffee\012\uffee\014\uffee\017" +
    "\uffee\020\uffee\023\uffee\024\uffee\026\uffee\027\uffee\030\uffee" +
    "\031\uffee\032\uffee\033\uffee\034\uffee\035\uffee\036\uffee\037" +
    "\uffee\040\uffee\041\uffee\044\uffee\045\uffee\046\uffee\047\uffee" +
    "\050\uffee\052\uffee\001\002\000\024\004\056\005\054\006" +
    "\055\007\050\010\051\011\053\025\046\030\057\046\030" +
    "\001\002\000\064\004\ufff2\012\ufff2\014\ufff2\017\ufff2\020" +
    "\ufff2\023\ufff2\024\ufff2\026\ufff2\027\ufff2\030\ufff2\031\ufff2" +
    "\032\ufff2\033\ufff2\034\ufff2\035\ufff2\036\ufff2\037\ufff2\040" +
    "\ufff2\041\ufff2\044\ufff2\045\ufff2\046\ufff2\047\ufff2\050\ufff2" +
    "\052\ufff2\001\002\000\064\004\ufff0\012\ufff0\014\ufff0\017" +
    "\ufff0\020\ufff0\023\ufff0\024\ufff0\026\ufff0\027\ufff0\030\ufff0" +
    "\031\ufff0\032\ufff0\033\ufff0\034\ufff0\035\ufff0\036\ufff0\037" +
    "\ufff0\040\ufff0\041\ufff0\044\ufff0\045\ufff0\046\ufff0\047\ufff0" +
    "\050\ufff0\052\ufff0\001\002\000\066\004\uffef\011\101\012" +
    "\uffef\014\uffef\017\uffef\020\uffef\023\uffef\024\uffef\026\uffef" +
    "\027\uffef\030\uffef\031\uffef\032\uffef\033\uffef\034\uffef\035" +
    "\uffef\036\uffef\037\uffef\040\uffef\041\uffef\044\uffef\045\uffef" +
    "\046\uffef\047\uffef\050\uffef\052\uffef\001\002\000\024\004" +
    "\056\005\054\006\055\007\050\010\051\011\053\025\046" +
    "\030\057\046\030\001\002\000\064\004\uffbd\012\uffbd\014" +
    "\uffbd\017\uffbd\020\uffbd\023\uffbd\024\uffbd\026\072\027\uffbd" +
    "\030\uffbd\031\uffbd\032\uffbd\033\061\034\uffbd\035\uffbd\036" +
    "\uffbd\037\uffbd\040\uffbd\041\064\044\uffbd\045\uffbd\046\uffbd" +
    "\047\uffbd\050\071\052\uffbd\001\002\000\024\004\uffce\005" +
    "\uffce\006\uffce\007\uffce\010\uffce\011\uffce\025\uffce\030\uffce" +
    "\046\uffce\001\002\000\024\004\uffd4\005\uffd4\006\uffd4\007" +
    "\uffd4\010\uffd4\011\uffd4\025\uffd4\030\uffd4\046\uffd4\001\002" +
    "\000\024\004\uffd6\005\uffd6\006\uffd6\007\uffd6\010\uffd6\011" +
    "\uffd6\025\uffd6\030\uffd6\046\uffd6\001\002\000\024\004\uffcf" +
    "\005\uffcf\006\uffcf\007\uffcf\010\uffcf\011\uffcf\025\uffcf\030" +
    "\uffcf\046\uffcf\001\002\000\024\004\uffd7\005\uffd7\006\uffd7" +
    "\007\uffd7\010\uffd7\011\uffd7\025\uffd7\030\uffd7\046\uffd7\001" +
    "\002\000\024\004\056\005\054\006\055\007\050\010\051" +
    "\011\053\025\046\030\057\046\030\001\002\000\024\004" +
    "\uffd1\005\uffd1\006\uffd1\007\uffd1\010\uffd1\011\uffd1\025\uffd1" +
    "\030\uffd1\046\uffd1\001\002\000\024\004\uffd8\005\uffd8\006" +
    "\uffd8\007\uffd8\010\uffd8\011\uffd8\025\uffd8\030\uffd8\046\uffd8" +
    "\001\002\000\024\004\uffd0\005\uffd0\006\uffd0\007\uffd0\010" +
    "\uffd0\011\uffd0\025\uffd0\030\uffd0\046\uffd0\001\002\000\024" +
    "\004\uffd3\005\uffd3\006\uffd3\007\uffd3\010\uffd3\011\uffd3\025" +
    "\uffd3\030\uffd3\046\uffd3\001\002\000\024\004\uffd9\005\uffd9" +
    "\006\uffd9\007\uffd9\010\uffd9\011\uffd9\025\uffd9\030\uffd9\046" +
    "\uffd9\001\002\000\024\004\uffd5\005\uffd5\006\uffd5\007\uffd5" +
    "\010\uffd5\011\uffd5\025\uffd5\030\uffd5\046\uffd5\001\002\000" +
    "\024\004\uffdb\005\uffdb\006\uffdb\007\uffdb\010\uffdb\011\uffdb" +
    "\025\uffdb\030\uffdb\046\uffdb\001\002\000\024\004\uffda\005" +
    "\uffda\006\uffda\007\uffda\010\uffda\011\uffda\025\uffda\030\uffda" +
    "\046\uffda\001\002\000\024\004\uffd2\005\uffd2\006\uffd2\007" +
    "\uffd2\010\uffd2\011\uffd2\025\uffd2\030\uffd2\046\uffd2\001\002" +
    "\000\064\004\uffc1\012\uffc1\014\uffc1\017\uffc1\020\uffc1\023" +
    "\065\024\063\026\072\027\077\030\067\031\074\032\062" +
    "\033\061\034\uffc1\035\075\036\076\037\073\040\070\041" +
    "\064\044\uffc1\045\uffc1\046\uffc1\047\uffc1\050\071\052\uffc1" +
    "\001\002\000\024\004\056\005\054\006\055\007\050\010" +
    "\051\011\053\025\046\030\057\046\030\001\002\000\042" +
    "\012\uffbc\020\uffbc\023\065\024\063\026\072\027\077\030" +
    "\067\031\074\032\062\033\061\035\075\036\076\037\073" +
    "\040\070\041\064\050\071\001\002\000\006\012\105\020" +
    "\104\001\002\000\024\004\056\005\054\006\055\007\050" +
    "\010\051\011\053\025\046\030\057\046\030\001\002\000" +
    "\064\004\uffba\012\uffba\014\uffba\017\uffba\020\uffba\023\uffba" +
    "\024\uffba\026\uffba\027\uffba\030\uffba\031\uffba\032\uffba\033" +
    "\uffba\034\uffba\035\uffba\036\uffba\037\uffba\040\uffba\041\uffba" +
    "\044\uffba\045\uffba\046\uffba\047\uffba\050\uffba\052\uffba\001" +
    "\002\000\042\012\uffbb\020\uffbb\023\065\024\063\026\072" +
    "\027\077\030\067\031\074\032\062\033\061\035\075\036" +
    "\076\037\073\040\070\041\064\050\071\001\002\000\040" +
    "\012\110\023\065\024\063\026\072\027\077\030\067\031" +
    "\074\032\062\033\061\035\075\036\076\037\073\040\070" +
    "\041\064\050\071\001\002\000\064\004\uffc0\012\uffc0\014" +
    "\uffc0\017\uffc0\020\uffc0\023\uffc0\024\uffc0\026\uffc0\027\uffc0" +
    "\030\uffc0\031\uffc0\032\uffc0\033\uffc0\034\uffc0\035\uffc0\036" +
    "\uffc0\037\uffc0\040\uffc0\041\uffc0\044\uffc0\045\uffc0\046\uffc0" +
    "\047\uffc0\050\uffc0\052\uffc0\001\002\000\020\004\042\013" +
    "\114\034\043\045\041\046\030\047\033\052\026\001\002" +
    "\000\022\004\uffcc\014\uffcc\034\uffcc\044\120\045\uffcc\046" +
    "\uffcc\047\uffcc\052\uffcc\001\002\000\022\004\uffcb\014\uffcb" +
    "\034\uffcb\044\uffcb\045\uffcb\046\uffcb\047\uffcb\052\uffcb\001" +
    "\002\000\016\004\042\034\043\045\041\046\030\047\033" +
    "\052\026\001\002\000\020\004\042\014\116\034\043\045" +
    "\041\046\030\047\033\052\026\001\002\000\022\004\uffca" +
    "\014\uffca\034\uffca\044\uffca\045\uffca\046\uffca\047\uffca\052" +
    "\uffca\001\002\000\020\004\uffe7\014\uffe7\034\uffe7\045\uffe7" +
    "\046\uffe7\047\uffe7\052\uffe7\001\002\000\020\004\042\013" +
    "\114\034\043\045\041\046\030\047\033\052\026\001\002" +
    "\000\022\004\uffcd\014\uffcd\034\uffcd\044\uffcd\045\uffcd\046" +
    "\uffcd\047\uffcd\052\uffcd\001\002\000\064\004\uffbe\012\uffbe" +
    "\014\uffbe\017\uffbe\020\uffbe\023\uffbe\024\uffbe\026\uffbe\027" +
    "\uffbe\030\uffbe\031\uffbe\032\uffbe\033\uffbe\034\uffbe\035\uffbe" +
    "\036\uffbe\037\uffbe\040\uffbe\041\uffbe\044\uffbe\045\uffbe\046" +
    "\uffbe\047\uffbe\050\uffbe\052\uffbe\001\002\000\006\042\127" +
    "\043\125\001\002\000\034\004\ufff9\012\ufff9\013\ufff9\014" +
    "\ufff9\017\ufff9\020\ufff9\022\ufff9\034\ufff9\044\ufff9\045\ufff9" +
    "\046\ufff9\047\ufff9\052\ufff9\001\002\000\036\004\ufff7\012" +
    "\ufff7\013\ufff7\014\ufff7\015\130\017\ufff7\020\ufff7\022\ufff7" +
    "\034\ufff7\044\ufff7\045\ufff7\046\ufff7\047\ufff7\052\ufff7\001" +
    "\002\000\032\004\ufff6\012\ufff6\014\ufff6\017\ufff6\020\ufff6" +
    "\022\ufff6\034\ufff6\044\ufff6\045\ufff6\046\ufff6\047\ufff6\052" +
    "\ufff6\001\002\000\036\004\ufff8\012\ufff8\013\ufff8\014\ufff8" +
    "\015\130\017\ufff8\020\ufff8\022\ufff8\034\ufff8\044\ufff8\045" +
    "\ufff8\046\ufff8\047\ufff8\052\ufff8\001\002\000\006\005\137" +
    "\016\136\001\002\000\036\004\uffff\012\uffff\013\uffff\014" +
    "\uffff\015\132\017\uffff\020\uffff\022\uffff\034\uffff\044\uffff" +
    "\045\uffff\046\uffff\047\uffff\052\uffff\001\002\000\006\005" +
    "\134\016\133\001\002\000\036\004\ufffd\012\ufffd\013\ufffd" +
    "\014\ufffd\015\ufffd\017\ufffd\020\ufffd\022\ufffd\034\ufffd\044" +
    "\ufffd\045\ufffd\046\ufffd\047\ufffd\052\ufffd\001\002\000\004" +
    "\016\135\001\002\000\036\004\ufffb\012\ufffb\013\ufffb\014" +
    "\ufffb\015\ufffb\017\ufffb\020\ufffb\022\ufffb\034\ufffb\044\ufffb" +
    "\045\ufffb\046\ufffb\047\ufffb\052\ufffb\001\002\000\036\004" +
    "\ufffc\012\ufffc\013\ufffc\014\ufffc\015\ufffc\017\ufffc\020\ufffc" +
    "\022\ufffc\034\ufffc\044\ufffc\045\ufffc\046\ufffc\047\ufffc\052" +
    "\ufffc\001\002\000\004\016\140\001\002\000\036\004\ufffa" +
    "\012\ufffa\013\ufffa\014\ufffa\015\ufffa\017\ufffa\020\ufffa\022" +
    "\ufffa\034\ufffa\044\ufffa\045\ufffa\046\ufffa\047\ufffa\052\ufffa" +
    "\001\002\000\036\004\ufffe\012\ufffe\013\ufffe\014\ufffe\015" +
    "\132\017\ufffe\020\ufffe\022\ufffe\034\ufffe\044\ufffe\045\ufffe" +
    "\046\ufffe\047\ufffe\052\ufffe\001\002\000\024\004\056\005" +
    "\054\006\055\007\050\010\051\011\053\025\046\030\057" +
    "\046\030\001\002\000\040\012\144\023\065\024\063\026" +
    "\072\027\077\030\067\031\074\032\062\033\061\035\075" +
    "\036\076\037\073\040\070\041\064\050\071\001\002\000" +
    "\004\013\145\001\002\000\016\004\042\034\043\045\041" +
    "\046\030\047\033\052\026\001\002\000\020\004\042\014" +
    "\147\034\043\045\041\046\030\047\033\052\026\001\002" +
    "\000\022\004\uffc9\014\uffc9\034\uffc9\044\uffc9\045\uffc9\046" +
    "\uffc9\047\uffc9\052\uffc9\001\002\000\006\002\uffe8\004\uffe8" +
    "\001\002\000\024\004\056\005\054\006\055\007\050\010" +
    "\051\011\153\025\046\030\057\046\030\001\002\000\060" +
    "\004\uffc8\014\uffc8\017\uffc8\023\065\024\063\026\072\027" +
    "\077\030\067\031\074\032\062\033\061\034\uffc8\035\075" +
    "\036\076\037\073\040\070\041\064\044\uffc8\045\uffc8\046" +
    "\uffc8\047\uffc8\050\071\052\uffc8\001\002\000\024\004\056" +
    "\005\054\006\055\007\050\010\051\011\053\025\046\030" +
    "\057\046\030\001\002\000\042\012\110\020\uffbc\023\065" +
    "\024\063\026\072\027\077\030\067\031\074\032\062\033" +
    "\061\035\075\036\076\037\073\040\070\041\064\050\071" +
    "\001\002\000\004\020\156\001\002\000\024\004\056\005" +
    "\054\006\055\007\050\010\051\011\053\025\046\030\057" +
    "\046\030\001\002\000\042\012\160\020\uffbb\023\065\024" +
    "\063\026\072\027\077\030\067\031\074\032\062\033\061" +
    "\035\075\036\076\037\073\040\070\041\064\050\071\001" +
    "\002\000\024\004\uffc7\014\uffc7\017\uffc7\034\uffc7\044\uffc7" +
    "\045\uffc7\046\uffc7\047\uffc7\052\uffc7\001\002\000\022\004" +
    "\uffde\014\uffde\034\uffde\044\uffde\045\uffde\046\uffde\047\uffde" +
    "\052\uffde\001\002\000\022\004\uffdc\014\uffdc\034\uffdc\044" +
    "\uffdc\045\uffdc\046\uffdc\047\uffdc\052\uffdc\001\002\000\024" +
    "\004\056\005\054\006\055\007\050\010\051\011\053\025" +
    "\046\030\057\046\030\001\002\000\006\012\165\020\104" +
    "\001\002\000\024\004\uffe1\014\uffe1\017\166\034\uffe1\044" +
    "\uffe1\045\uffe1\046\uffe1\047\uffe1\052\uffe1\001\002\000\022" +
    "\004\uffdf\014\uffdf\034\uffdf\044\uffdf\045\uffdf\046\uffdf\047" +
    "\uffdf\052\uffdf\001\002\000\004\004\170\001\002\000\004" +
    "\012\171\001\002\000\064\004\uffb9\012\uffb9\014\uffb9\017" +
    "\uffb9\020\uffb9\023\uffb9\024\uffb9\026\uffb9\027\uffb9\030\uffb9" +
    "\031\uffb9\032\uffb9\033\uffb9\034\uffb9\035\uffb9\036\uffb9\037" +
    "\uffb9\040\uffb9\041\uffb9\044\uffb9\045\uffb9\046\uffb9\047\uffb9" +
    "\050\uffb9\052\uffb9\001\002\000\022\004\uffe0\014\uffe0\034" +
    "\uffe0\044\uffe0\045\uffe0\046\uffe0\047\uffe0\052\uffe0\001\002" +
    "\000\006\042\127\043\125\001\002\000\004\013\uffed\001" +
    "\002\000\006\012\200\020\177\001\002\000\006\012\uffe9" +
    "\020\uffe9\001\002\000\006\042\127\043\125\001\002\000" +
    "\004\013\uffec\001\002\000\006\012\uffea\020\uffea\001\002" +
    "\000\006\012\ufff5\020\ufff5\001\002\000\006\002\uffb5\004" +
    "\uffb5\001\002\000\006\004\000\051\000\001\002" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() {return _action_table;}

  /** {@code reduce_goto} table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\202\000\010\002\006\003\003\004\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\003\011\031\012" +
    "\032\010\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\032\202\001\001" +
    "\000\002\001\001\000\006\007\015\010\017\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\201\001\001\000\004\012\023\001\001\000\006\005" +
    "\123\006\173\001\001\000\002\001\001\000\022\007\033" +
    "\013\036\014\037\015\034\017\026\020\030\021\031\027" +
    "\035\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\007\033\014\116\015\034\017\026\020\030\021" +
    "\031\027\035\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\011\044\015" +
    "\051\023\046\001\001\000\002\001\001\000\010\011\044" +
    "\015\051\023\121\001\001\000\004\022\065\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\011\044\015\051\023\106\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\011\044\015\051" +
    "\023\057\001\001\000\004\022\065\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\011\044\015\051\023\077\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\022\065\001\001\000\012\011\044\015\051\023\101\030" +
    "\102\001\001\000\004\022\065\001\001\000\002\001\001" +
    "\000\010\011\044\015\051\023\105\001\001\000\002\001" +
    "\001\000\004\022\065\001\001\000\004\022\065\001\001" +
    "\000\002\001\001\000\022\007\033\014\112\015\034\017" +
    "\026\020\030\021\031\024\111\027\035\001\001\000\002" +
    "\001\001\000\002\001\001\000\022\007\033\013\114\014" +
    "\037\015\034\017\026\020\030\021\031\027\035\001\001" +
    "\000\020\007\033\014\116\015\034\017\026\020\030\021" +
    "\031\027\035\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\007\033\014\112\015\034\017\026\020\030\021" +
    "\031\024\120\027\035\001\001\000\002\001\001\000\004" +
    "\022\065\001\001\000\006\005\123\006\125\001\001\000" +
    "\002\001\001\000\004\025\140\001\001\000\002\001\001" +
    "\000\004\025\130\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\011\044\015\051" +
    "\023\142\001\001\000\004\022\065\001\001\000\002\001" +
    "\001\000\022\007\033\013\145\014\037\015\034\017\026" +
    "\020\030\021\031\027\035\001\001\000\020\007\033\014" +
    "\116\015\034\017\026\020\030\021\031\027\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\011\044\015" +
    "\051\023\151\001\001\000\004\022\065\001\001\000\012" +
    "\011\044\015\051\023\153\030\154\001\001\000\004\022" +
    "\065\001\001\000\002\001\001\000\010\011\044\015\051" +
    "\023\156\001\001\000\004\022\065\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\011\044" +
    "\015\051\023\101\030\163\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\005" +
    "\123\006\175\016\174\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\005\123\006\200\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to {@code reduce_goto} table. */
  @Override
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack<java_cup.runtime.Symbol> stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 0;}

  /** {@code EOF} Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** {@code error} Symbol index. */
  @Override
  public int error_sym() {return 1;}



    // Connect this parser to a scanner!
    //Lexer s;
    CodeWriterSExpPrinter printer;
    parser(CodeWriterSExpPrinter printer){ this.printer=printer; }


/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
    private final parser parser;

    /** Constructor */
    CUP$parser$actions(parser parser) {
        this.parser = parser;
    }

    /** Method with the actual generated action code for actions 0 to 77. */
    public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            /* Symbol object for return from actions */
            java_cup.runtime.Symbol CUP$parser$result;

        /* select the action based on the action number */
        switch (CUP$parser$act_num) {
        /*. . . . . . . . . . . . . . . . . . . .*/
        case 0: // $START ::= program EOF 
            {
                Object RESULT = null;
                int start_valleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int start_valright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Object start_val = CUP$parser$stack.elementAt(CUP$parser$top-1).<Object> value();
                RESULT = start_val;
                CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            /* ACCEPT */
            CUP$parser$parser.done_parsing();
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 1: // singleUse ::= USE IDENTIFIER 
            {
                Object RESULT = null;
                int idleft = CUP$parser$stack.peek().left;
                int idright = CUP$parser$stack.peek().right;
                Object id = CUP$parser$stack.peek().<Object> value();
                 RESULT = "(use "+id+")\n"; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("singleUse",1, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 2: // arrayType ::= INT brackets 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",3, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 3: // arrayType ::= BOOL brackets 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("arrayType",3, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 4: // brackets ::= brackets LBRACK RBRACK 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",19, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 5: // brackets ::= LBRACK RBRACK 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",19, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 6: // brackets ::= brackets LBRACK INTEGER_LITERAL RBRACK 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",19, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 7: // brackets ::= LBRACK INTEGER_LITERAL RBRACK 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("brackets",19, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 8: // type ::= arrayType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",4, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 9: // type ::= INT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",4, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 10: // type ::= BOOL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("type",4, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 11: // argumentWithType ::= IDENTIFIER COLON type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentWithType",5, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 12: // argumentsWithType ::= argumentsWithType COMMA argumentWithType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",6, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 13: // argumentsWithType ::= argumentWithType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentsWithType",6, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 14: // argument ::= BOOLEAN_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",7, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 15: // argument ::= INTEGER_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",7, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 16: // argument ::= CHARACTER_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",7, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 17: // argument ::= STRING_LITERAL 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",7, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 18: // argument ::= IDENTIFIER 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",7, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 19: // argument ::= functionCall 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("argument",7, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 20: // functionReturnType ::= COLON type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 21: // functionReturnType ::= COLON LPAREN typesList RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 22: // functionReturnType ::= 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionReturnType",8, CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 23: // typesList ::= typesList COMMA type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",12, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 24: // typesList ::= type 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("typesList",12, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 25: // method ::= IDENTIFIER LPAREN argumentsWithType RPAREN functionReturnType LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-7).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-7).right;
                Object id = CUP$parser$stack.elementAt(CUP$parser$top-7).<Object> value();
                 RESULT = id; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("method",24, CUP$parser$stack.elementAt(CUP$parser$top-7), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 26: // multipleStatements ::= multipleStatements statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("multipleStatements",9, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 27: // multipleStatements ::= statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("multipleStatements",9, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 28: // statement ::= functionCall 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 29: // statement ::= assignment 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 30: // statement ::= ifStatement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 31: // statement ::= whileStatement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 32: // statement ::= RETURN LPAREN expressions RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 33: // statement ::= assignment SEMICOLON 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 34: // statement ::= RETURN LPAREN expressions RPAREN SEMICOLON 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 35: // statement ::= functionCall SEMICOLON 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 36: // statement ::= argumentWithType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 37: // statement ::= argumentWithType SEMICOLON 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",10, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 38: // operator ::= EQEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 39: // operator ::= GTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 40: // operator ::= LTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 41: // operator ::= NOTEQ 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 42: // operator ::= GT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 43: // operator ::= LT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 44: // operator ::= AND 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 45: // operator ::= OR 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 46: // operator ::= MULT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 47: // operator ::= PLUS 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 48: // operator ::= MINUS 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 49: // operator ::= DIV 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 50: // operator ::= HIGHMULT 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 51: // operator ::= MOD 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("operator",16, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 52: // ifStatement ::= IF LPAREN expression RPAREN oneOrMorestatements ELSE oneOrMorestatements 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("ifStatement",14, CUP$parser$stack.elementAt(CUP$parser$top-6), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 53: // ifStatement ::= IF LPAREN expression RPAREN oneOrMorestatements 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("ifStatement",14, CUP$parser$stack.elementAt(CUP$parser$top-4), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 54: // oneOrMorestatements ::= statement 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("oneOrMorestatements",18, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 55: // oneOrMorestatements ::= LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("oneOrMorestatements",18, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 56: // whileStatement ::= WHILE LPAREN expression RPAREN LBRACE multipleStatements RBRACE 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("whileStatement",15, CUP$parser$stack.elementAt(CUP$parser$top-6), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 57: // assignment ::= variable EQ expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",13, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 58: // assignment ::= variable EQ LPAREN expressions COMMA expression RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",13, CUP$parser$stack.elementAt(CUP$parser$top-6), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 59: // variables ::= variables COMMA variable 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("variables",20, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 60: // variables ::= variable 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("variables",20, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 61: // variable ::= UNDERSCORE 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("variable",21, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 62: // variable ::= IDENTIFIER 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("variable",21, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 63: // variable ::= argumentWithType 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("variable",21, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 64: // expression ::= expression operator expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",17, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 65: // expression ::= LPAREN expression RPAREN 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",17, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 66: // expression ::= argument 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",17, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 67: // expression ::= NOT expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",17, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 68: // expression ::= MINUS expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",17, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 69: // expressions ::= expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expressions",22, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 70: // expressions ::= expressions COMMA expression 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expressions",22, CUP$parser$stack.elementAt(CUP$parser$top-2), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 71: // functionCall ::= IDENTIFIER LPAREN expressions RPAREN 
            {
                Object RESULT = null;
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-3).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-3).right;
                Object id = CUP$parser$stack.elementAt(CUP$parser$top-3).<Object> value();
                int esleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int esright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Object es = CUP$parser$stack.elementAt(CUP$parser$top-1).<Object> value();
                 RESULT = "("+bs+")"; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionCall",11, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 72: // functionCall ::= LENGTH LPAREN IDENTIFIER RPAREN 
            {
                Object RESULT = null;
                int idleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int idright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Object id = CUP$parser$stack.elementAt(CUP$parser$top-1).<Object> value();
                 RESULT = "length("; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("functionCall",11, CUP$parser$stack.elementAt(CUP$parser$top-3), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 73: // program ::= uses methods 
            {
                Object RESULT = null;
                int ssleft = CUP$parser$stack.elementAt(CUP$parser$top-1).left;
                int ssright = CUP$parser$stack.elementAt(CUP$parser$top-1).right;
                Object ss = CUP$parser$stack.elementAt(CUP$parser$top-1).<Object> value();
                int msleft = CUP$parser$stack.peek().left;
                int msright = CUP$parser$stack.peek().right;
                Object ms = CUP$parser$stack.peek().<Object> value();
                 RESULT = "("+ss+")"; 
                CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 74: // uses ::= uses singleUse 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("uses",2, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 75: // uses ::= singleUse 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("uses",2, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 76: // methods ::= methods method 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("methods",23, CUP$parser$stack.elementAt(CUP$parser$top-1), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 77: // methods ::= method 
            {
                Object RESULT = null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("methods",23, CUP$parser$stack.peek(), CUP$parser$stack.peek(), RESULT);
            }
            return CUP$parser$result;

        /* . . . . . .*/
        default:
            throw new Exception(
                  "Invalid action number " + CUP$parser$act_num + " found in internal parse table");

        }
    } /* end of method */

    /** Method splitting the generated action code into several parts. */
    public final java_cup.runtime.Symbol CUP$parser$do_action(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack<java_cup.runtime.Symbol> CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception {
            return CUP$parser$do_action_part00000000(
                           CUP$parser$act_num,
                           CUP$parser$parser,
                           CUP$parser$stack,
                           CUP$parser$top);
    }
}

}
