
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package zr54.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNDERSCORE = 41;
  public static final int LENGTH = 37;
  public static final int LT = 19;
  public static final int INTEGER_LITERAL = 4;
  public static final int error = 1;
  public static final int INT = 33;
  public static final int MINUS = 23;
  public static final int RETURN = 38;
  public static final int MULT = 21;
  public static final int BOOLEAN_LITERAL = 7;
  public static final int SEMICOLON = 14;
  public static final int LTEQ = 30;
  public static final int ELSE = 35;
  public static final int IDENTIFIER = 2;
  public static final int EOF = 0;
  public static final int IF = 27;
  public static final int INTEGER = 3;
  public static final int COMMA = 15;
  public static final int OR = 25;
  public static final int MOD = 26;
  public static final int CHARACTER_LITERAL = 6;
  public static final int USE = 40;
  public static final int LPAREN = 8;
  public static final int COLON = 16;
  public static final int RPAREN = 9;
  public static final int EQ = 17;
  public static final int HIGHMULT = 32;
  public static final int GT = 18;
  public static final int NOTEQ = 31;
  public static final int DIV = 39;
  public static final int RBRACK = 13;
  public static final int NOT = 20;
  public static final int RBRACE = 11;
  public static final int LBRACK = 12;
  public static final int BOOL = 34;
  public static final int AND = 24;
  public static final int EQEQ = 28;
  public static final int GTEQ = 29;
  public static final int STRING_LITERAL = 5;
  public static final int WHILE = 36;
  public static final int LBRACE = 10;
  public static final int PLUS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "INTEGER",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "CHARACTER_LITERAL",
  "BOOLEAN_LITERAL",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "COLON",
  "EQ",
  "GT",
  "LT",
  "NOT",
  "MULT",
  "PLUS",
  "MINUS",
  "AND",
  "OR",
  "MOD",
  "IF",
  "EQEQ",
  "GTEQ",
  "LTEQ",
  "NOTEQ",
  "HIGHMULT",
  "INT",
  "BOOL",
  "ELSE",
  "WHILE",
  "LENGTH",
  "RETURN",
  "DIV",
  "USE",
  "UNDERSCORE"
  };
}

