// A stub for a Xi CUP specification.
/* Part of code from http://www2.cs.tum.edu/projekte/cup/examples.php */
package zr54.parser;

import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*; 
import zr54.lexer.*;
import zr54.parser.*;

parser code {:
    // Connect this parser to a scanner!
    //Lexer s;
    public CodeWriterSExpPrinter printer;
    public parser(CodeWriterSExpPrinter printer){ this.printer=printer; }

:}

/* define how to connect to the scanner! */
//init with {: s.init(); :};
//scan with {: return s.next_token(); :};

// You might want to add types to these declarations.
terminal IDENTIFIER, INTEGER_LITERAL, STRING_LITERAL, CHARACTER_LITERAL, BOOLEAN_LITERAL, LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK, SEMICOLON, COMMA, COLON, EQ, GT, LT, NOT, MULT, PLUS, MINUS, AND, OR, MOD, IF, EQEQ, GTEQ, LTEQ, NOTEQ, HIGHMULT, INT, BOOL, ELSE, WHILE, LENGTH, RETURN, DIV, USE, UNDERSCORE;

// You might want to add types to these declarations.
nonterminal AstNode program, singleUse, uses, arrayType, type, argumentWithType, argumentsWithType, optionalArgumentsWithType, argument, functionReturnType , statements, optionalStatements, statement, functionCall, typesList, assignment, ifStatement, whileStatement, operator, expression, brackets, variables, variable, expressions, methods, method, arrayLiteral, optionalSemicolon, arrayIndices, block, optionalReturn;
// Add more nonterminals here...




precedence nonassoc ELSE;
precedence nonassoc EQ;
precedence left OR;
precedence left AND;
precedence left EQEQ, NOTEQ;
precedence left LT, LTEQ, GTEQ, GT;
precedence left PLUS, MINUS;
precedence left MULT, HIGHMULT, DIV, MOD;
precedence nonassoc NOT;


start with program;

// Recognizes "Hello World!", but not much else.
/*program ::= USE IDENTIFIER IDENTIFIER LPAREN IDENTIFIER COLON
  INT LBRACK RBRACK LBRACK RBRACK RPAREN
  LBRACE IDENTIFIER LPAREN STRING_LITERAL RPAREN RBRACE;*/

singleUse           ::= USE IDENTIFIER:id            {: RESULT = new AstNode("useSpecifier", "", new AstNode("USE", "use"), new AstNode("IDENTIFIER", id.toString())); :}    
                      ;
arrayType           ::= arrayType:at brackets:br							{: RESULT = new AstNode("arrayType", "[]", at); RESULT.addGrandChildren(br); :}
					            | INT brackets:br    							  	{: RESULT = new AstNode("arrayType", "[]", new AstNode("INT", "int")); RESULT.addGrandChildren(br); :}
                      | BOOL brackets:br							    		{: RESULT = new AstNode("arrayType", "[]", new AstNode("BOOL", "bool")); RESULT.addGrandChildren(br); :}
                      ;
arrayLiteral        ::= LBRACE expressions:es RBRACE          {: RESULT = new AstNode("arrayLiteral", ""); RESULT.addGrandChildren(es); :}
                      ;

brackets            ::= LBRACK expression:es  RBRACK {: RESULT = new AstNode("brackets", ""); RESULT.addGrandChildren(es); :}
					            | LBRACK RBRACK
                      ;

type                ::= arrayType:a             {: RESULT = a; :}
                      | INT                 {: RESULT = new AstNode("INT", "int"); :}
                      | BOOL                {: RESULT = new AstNode("BOOL", "bool"); :}
                      ;

argumentWithType    ::= IDENTIFIER:id COLON type:t      {: RESULT = new AstNode("argumentWithType", id.toString()); RESULT.addChild(t); :}
            ; 
argumentsWithType   ::= argumentsWithType:as COMMA argumentWithType:a {: RESULT = new AstNode("argumentsWithType", ""); RESULT.addGrandChildren(as); RESULT.addChild(a); :}
                      | argumentWithType:a        {: RESULT = new AstNode("argumentsWithType", "", a); :}       
                      ;
argument            ::= BOOLEAN_LITERAL:bl        {: RESULT = new AstNode("BOOLEAN_LITERAL", bl.toString()); :}
                      | INTEGER_LITERAL:il        {: RESULT = new AstNode("INTEGER_LITERAL", il.toString()); :}
                      | CHARACTER_LITERAL:cl      {: RESULT = new AstNode("CHARACTER_LITERAL", "\'"+cl.toString()+"\'"); :}
                      | STRING_LITERAL:sl       {: RESULT = new AstNode("STRING_LITERAL", "\""+sl.toString()+"\""); :}
                      | IDENTIFIER:id         {: RESULT = new AstNode("IDENTIFIER", id.toString()); :}
                      | functionCall:fc         {: RESULT = fc; :}
                      | arrayLiteral:al         {: RESULT = new AstNode("argument", ""); RESULT.addGrandChildren(al); :}
                      | arrayIndices:ai         {: RESULT = new AstNode("argument", "", ai); :}
                      ;
arrayIndices        ::= IDENTIFIER:id LBRACK expression:a RBRACK  {: RESULT = new AstNode("arrayIndices", "[]", new AstNode("IDENTIFIER", id.toString())); RESULT.addGrandChildren(a); :}
                      | arrayIndices:ai LBRACK expression:a RBRACK  {: RESULT = new AstNode("arrayIndices", "[]", ai); RESULT.addGrandChildren(a); :}
                      ;
functionReturnType  ::= COLON typesList:tl          {: RESULT = new AstNode("functionReturnType", ""); RESULT.addGrandChildren(tl); :} 
                      |	{: RESULT = new AstNode("forceParen", ""); :}
                      ;
typesList           ::= typesList:tl COMMA type:t   {: RESULT = new AstNode("typesList", ""); RESULT.addGrandChildren(tl); RESULT.addChild(t); :}  
            | type:t              {: RESULT = new AstNode("typesList", ""); RESULT.addChild(t); :}
            ;       


method              ::= IDENTIFIER:id LPAREN optionalArgumentsWithType:a RPAREN functionReturnType:r LBRACE optionalStatements:os optionalReturn:re RBRACE 
						{: RESULT = new AstNode("method", id.toString()); RESULT.addChild(a); RESULT.addChild(r); RESULT.addChild(os); RESULT.addChild(re); :}
                    
                      ;
optionalStatements  ::= statements:s {: RESULT = s; :}
                      |
                      ;
optionalArgumentsWithType::=  argumentsWithType:a {: RESULT = a; :}
                      | {: RESULT = new AstNode("forceParen", ""); :}
                      ;                     
statements  ::= statements:ms statement:s     {: RESULT = new AstNode("statements", ""); RESULT.addGrandChildren(ms); RESULT.addGrandChildren(s); :}
                      | statement:s             {: RESULT = new AstNode("statements", ""); RESULT.addGrandChildren(s); :}
                      ;
statement           ::= functionCall:f optionalSemicolon   {: RESULT = new AstNode("statement", "", f); :}
                      | assignment:a optionalSemicolon   {: RESULT = new AstNode("statement", "", a); :} 
                      | ifStatement:s               {: RESULT = new AstNode("statement", "", s); :}   
                      | whileStatement:s            {: RESULT = new AstNode("statement", "", s); :}
                      //| RETURN expressions:e optionalSemicolon {: RESULT = new AstNode("statement", "return"); RESULT.addGrandChildren(e); :} 
                      | argumentWithType:a optionalSemicolon  {: RESULT = new AstNode("statement", "", a); :}
                      | block: b  {: RESULT = b; :}
                      ; 
optionalReturn      ::= RETURN expressions:e optionalSemicolon {: RESULT = new AstNode("statement", "return"); RESULT.addGrandChildren(e); :} 
                      | 
                      ;                
optionalSemicolon   ::= SEMICOLON 
                      | 
                      ;

operator            ::= EQEQ    {: RESULT = new AstNode("EQEQ", "=="); :} 
            | GTEQ    {: RESULT = new AstNode("GTEQ", ">="); :} 
            | LTEQ    {: RESULT = new AstNode("LTEQ", "<="); :} 
            | NOTEQ   {: RESULT = new AstNode("NOTEQ", "!="); :} 
            | GT      {: RESULT = new AstNode("GT", ">"); :} 
            | LT      {: RESULT = new AstNode("LT", "<"); :} 
            | AND     {: RESULT = new AstNode("AND", "&"); :} 
            | OR      {: RESULT = new AstNode("OR", "|"); :} 
                      | MULT    {: RESULT = new AstNode("MULT", "*"); :} 
                      | PLUS    {: RESULT = new AstNode("PLUS", "+"); :} 
                      | MINUS     {: RESULT = new AstNode("MINUS", "-"); :} 
                      | DIV     {: RESULT = new AstNode("DIV", "/"); :} 
                      | HIGHMULT  {: RESULT = new AstNode("HIGHMULT", "*>>"); :} 
                      | MOD     {: RESULT = new AstNode("MOD", "%"); :} 
                      ; // incomplete

ifStatement         ::= IF LPAREN expression:e RPAREN statement:s1 ELSE statement:s2  {: RESULT = new AstNode("ifStatement", "if"); RESULT.addGrandChildren(e); RESULT.addGrandChildren(s1); RESULT.addGrandChildren(s2); :}
                      | IF LPAREN expression:e RPAREN statement:s       {: RESULT = new AstNode("ifStatement", "if"); RESULT.addGrandChildren(e); RESULT.addGrandChildren(s); :}
                      ;

whileStatement      ::= WHILE LPAREN expression:e RPAREN statement:s  {: RESULT = new AstNode("whileStatment", "while"); RESULT.addGrandChildren(e); RESULT.addChild(s); :}
            ;

assignment          ::= variables:vs COMMA variable:v EQ expression:e   {: AstNode node = new AstNode("variables", ""); node.addGrandChildren(vs); node.addChild(v); RESULT = new AstNode("assignment", "=", node); RESULT.addGrandChildren(e); :}
                      | variable:v EQ expression:e						{: RESULT = new AstNode("assignment", "="); RESULT.addChild(v);  RESULT.addGrandChildren(e); :}
                      ;
                      
variables           ::= variables:vs COMMA variable:v     {: RESULT = new AstNode("variables", ""); RESULT.addGrandChildren(vs); RESULT.addChild(v); :}
                      | variable:v                {: RESULT = new AstNode("variables", ""); RESULT.addChild(v); :} 
                      ;
variable            ::= UNDERSCORE                {: RESULT = new AstNode("UNDERSCORE", "_"); :}
                      | IDENTIFIER:id                {: RESULT = new AstNode("IDENTIFIER", id.toString()); :}
                      | argumentWithType:a        {: RESULT = a; :}
                      | arrayIndices:a   		  {: RESULT = a; :}
                      ;
expression          ::= expression:e1 operator:o expression:e2      {: RESULT = new AstNode("expression", "", o); o.addGrandChildren(e1); o.addGrandChildren(e2); :}
                      | LPAREN expression:e RPAREN            {: RESULT = new AstNode("expression", ""); RESULT.addGrandChildren(e); :}
                      | argument:a                    {: RESULT = new AstNode("expression", ""); RESULT.addChild(a); :}
                      | NOT expression:e                {: AstNode n = new AstNode("NOT", "!"); n.addGrandChildren(e); RESULT = new AstNode("expression", "", n); :}            
                      | MINUS expression:e                {: AstNode n = new AstNode("MINUS", "-"); n.addGrandChildren(e); RESULT = new AstNode("expression", "", n); :}
                      ;
expressions         ::= expression:e                  {: RESULT = new AstNode("expressions", ""); RESULT.addGrandChildren(e); :} 
                      | expressions:es COMMA expression:e       {: RESULT = new AstNode("expressions", ""); RESULT.addGrandChildren(es); RESULT.addGrandChildren(e); :}
                      ;
functionCall        ::= IDENTIFIER:id LPAREN expressions:es RPAREN    {: RESULT = new AstNode("functionCall", id.toString()); RESULT.addGrandChildren(es); :}
                      | IDENTIFIER:id LPAREN RPAREN    {: RESULT = new AstNode("functionCall", id.toString());:}
                      | LENGTH LPAREN IDENTIFIER:id RPAREN              {: RESULT = new AstNode("functionCall", "length", new AstNode("IDENTIFIER", id.toString())); :}
                      ;
program             ::= uses:us  methods:ms                             {: RESULT = new AstNode("program", "", us, ms); :}
                      | uses:us                     {: RESULT = new AstNode("program", "", us, new AstNode("methods", "")); :}
                      | methods:ms                    {: RESULT = new AstNode("program", "", new AstNode("forceParen", ""), ms); :}
                      |                           {: RESULT = new AstNode("program", "", new AstNode("uses", ""), new AstNode("methods", "")); :}
                      | error:e   {: Lexer l = (Lexer)getScanner(); int line = l.getLine(); int column = l.getColumn(); RESULT = new AstNode("error", new Token( line,column,l.yytext())); :}
                      ; 
uses                ::= uses:us singleUse:su                            {: RESULT = new AstNode("uses", ""); RESULT.addGrandChildren(us); RESULT.addChild(su); :}
                      | singleUse:su                                    {: RESULT = new AstNode("uses", "", su); :}
                      ; 
methods             ::= methods:ms method:m               {: RESULT = new AstNode("methods", ""); RESULT.addGrandChildren(ms); RESULT.addChild(m); :} 
                      | method:m                                        {: RESULT = new AstNode("methods", "", m); :}
                      ;
block               ::= LBRACE optionalStatements:s RBRACE      {: RESULT = s; :}
                      ;