// A stub for a Xi CUP specification.
/* Part of code from http://www2.cs.tum.edu/projekte/cup/examples.php */
package zr54.parser;
import zr54.lexer.*;
import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*; 


parser code {:
    // Connect this parser to a scanner!
    //Lexer s;
    CodeWriterSExpPrinter printer;
    parser(CodeWriterSExpPrinter printer){ this.printer=printer; }
:}

/* define how to connect to the scanner! */
//init with {: s.init(); :};
//scan with {: return s.next_token(); :};

// You might want to add types to these declarations.
terminal IDENTIFIER, INTEGER_LITERAL, STRING_LITERAL, CHARACTER_LITERAL, BOOLEAN_LITERAL, LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK, SEMICOLON, COMMA, COLON, EQ, GT, LT, NOT, MULT, PLUS, MINUS, AND, OR, MOD, IF, EQEQ, GTEQ, LTEQ, NOTEQ, HIGHMULT, INT, BOOL, ELSE, WHILE, LENGTH, RETURN, DIV, USE, UNDERSCORE;

// You might want to add types to these declarations.
nonterminal AstNode program, singleUse, uses, arrayType, type, argumentWithType, argumentsWithType, argument, functionReturnType , multipleStatements, statement, functionCall, typesList, assignment, ifStatement, whileStatement, operator, expression, oneOrMorestatements, brackets, variables, variable, expressions, methods, method, arrayLiteral, optionalSemicolon;
// Add more nonterminals here...




precedence nonassoc ELSE;
precedence nonassoc EQ;
precedence left OR;
precedence left AND;
precedence left EQEQ, NOTEQ;
precedence left LT, LTEQ, GTEQ, GT;
precedence left PLUS, MINUS;
precedence left MULT, HIGHMULT, DIV, MOD;
precedence nonassoc NOT;


start with program;

// Recognizes "Hello World!", but not much else.
/*program ::= USE IDENTIFIER IDENTIFIER LPAREN IDENTIFIER COLON
  INT LBRACK RBRACK LBRACK RBRACK RPAREN
  LBRACE IDENTIFIER LPAREN STRING_LITERAL RPAREN RBRACE;*/

singleUse           ::= USE IDENTIFIER:id                                    {: RESULT = new AstNode("useSpecifier", "", new AstNode("USE", "use"), new AstNode("IDENTIFIER", id.toString())); :}    
                      ;
arrayType           ::= INT brackets
                      | BOOL brackets
                      ;
arrayLiteral        ::= LBRACE expressions RBRACE
                      ;

brackets            ::= brackets LBRACK RBRACK
                      | LBRACK RBRACK
                      | brackets LBRACK INTEGER_LITERAL RBRACK
                      | LBRACK INTEGER_LITERAL RBRACK
                      ;
type                ::= arrayType
                      | INT
                      | BOOL
                      ;
argumentWithType    ::= IDENTIFIER COLON type;
argumentsWithType   ::= argumentsWithType COMMA argumentWithType
                      | argumentWithType;
argument            ::= BOOLEAN_LITERAL
                      | INTEGER_LITERAL
                      | CHARACTER_LITERAL
                      | STRING_LITERAL
                      | IDENTIFIER
                      | functionCall
                      | arrayLiteral
                      ;

functionReturnType  ::= COLON typesList
                      |;
typesList           ::= typesList COMMA type | type;


method              ::= IDENTIFIER:id LPAREN argumentsWithType RPAREN functionReturnType
                          LBRACE multipleStatements RBRACE    
                          ;
multipleStatements  ::= multipleStatements statement
                      | statement;
statement           ::= functionCall optionalSemicolon
                      | assignment optionalSemicolon
                      | ifStatement 
                      | whileStatement 
                      | RETURN expressions optionalSemicolon
                      | argumentWithType optionalSemicolon
                      ; 
optionalSemicolon   ::= SEMICOLON
                      | 
                      ;
operator            ::= EQEQ		{: RESULT = new AstNode("EQEQ", "=="); :} 
					  | GTEQ		{: RESULT = new AstNode("GTEQ", ">="); :} 
					  | LTEQ		{: RESULT = new AstNode("LTEQ", "<="); :} 
					  | NOTEQ		{: RESULT = new AstNode("NOTEQ", "!="); :} 
					  | GT		 	{: RESULT = new AstNode("GT", ">"); :} 
					  | LT			{: RESULT = new AstNode("LT", "<"); :} 
					  | AND			{: RESULT = new AstNode("AND", "&"); :} 
					  | OR 			{: RESULT = new AstNode("OR", "|"); :} 
                      | MULT 		{: RESULT = new AstNode("MULT", "*"); :} 
                      | PLUS 		{: RESULT = new AstNode("PLUS", "+"); :} 
                      | MINUS 		{: RESULT = new AstNode("MINUS", "-"); :} 
                      | DIV 		{: RESULT = new AstNode("DIV", "/"); :} 
                      | HIGHMULT 	{: RESULT = new AstNode("HIGHMULT", "*>>"); :} 
                      | MOD			{: RESULT = new AstNode("MOD", "%"); :} 
                      ; // incomplete

ifStatement         ::= IF LPAREN expression RPAREN oneOrMorestatements ELSE oneOrMorestatements
                      | IF LPAREN expression RPAREN oneOrMorestatements
                      ;
oneOrMorestatements ::= statement										{: :}
                      | LBRACE multipleStatements RBRACE				{: RESULT = new AstNode("oneOrMoreStatements", ""); :}
                      ;
whileStatement      ::= WHILE LPAREN expression RPAREN LBRACE multipleStatements RBRACE		{: RESULT = new AstNode("whileStatment", ""); :}
						;	

assignment          ::= variable:v EQ expression:e									{: RESULT = new AstNode("assignment", "=", v); RESULT.addChild(v); RESULT.addGrandChildren(e); :}
                      ;
variables           ::= variables:vs COMMA variable:v			{: RESULT = new AstNode("variables", ""); RESULT.addGrandChildren(vs); RESULT.addChild(v); :}
                      | variable:v								{: RESULT = new AstNode("variables", "", v); :} 
                      ;
variable            ::= UNDERSCORE								{: RESULT = new AstNode("UNDERSCORE", "_"); :}
                      | IDENTIFIER								{: RESULT = new AstNode("IDENTIFIER", "id"); :}
                      | argumentWithType:a						{: RESULT = new AstNode("argumentWithType", ""); RESULT.addGrandChildren(a); :}
                      ;
expression          ::= expression:e1 operator:o expression:e2			{: RESULT = new AstNode("expression", "", o); o.addGrandChildren(e1); o.addGrandChildren(e2); :}
                      | LPAREN expression:e RPAREN						{: RESULT = new AstNode("expression", ""); RESULT.addGrandChildren(e); :}
                      | argument:a										{: RESULT = new AstNode("expression", ""); RESULT.addGrandChildren(a); :}
                      | NOT expression:e								{: AstNode n = new AstNode("NOT", "!"); n.addGrandChildren(e); RESULT = new AstNode("expression", "", n); :}						
                      | MINUS expression:e								{: AstNode n = new AstNode("MINUS", "-"); n.addGrandChildren(e); RESULT = new AstNode("expression", "", n); :}
                      ;
expressions         ::= expression:e									{: RESULT = new AstNode("expressions", "", e); :} 
                      | expressions:es COMMA expression:e				{: RESULT = new AstNode("expressions", "");	RESULT.addGrandChildren(es); RESULT.addChild(e); :}
                      ;
functionCall        ::= IDENTIFIER:id LPAREN expressions:es RPAREN		{: RESULT = new AstNode("functionCall", id.toString()); RESULT.addGrandChildren(es); :}
                      | LENGTH LPAREN IDENTIFIER:id RPAREN              {: RESULT = new AstNode("functionCall", "length", new AstNode("IDENTIFIER", id.toString())); :}
                      ;
program             ::= uses:us  methods:ms                             {: RESULT = new AstNode("program", "", us, ms); :}
                      | uses:us											{: RESULT = new AstNode("program", "", us, new AstNode("methods", "")); :}
                      | methods:ms										{: RESULT = new AstNode("program", "", new AstNode("uses", ""), ms); :}
                      |												    {: RESULT = new AstNode("program", "", new AstNode("uses", ""), new AstNode("methods", "")); :}
                      ; 
uses                ::= uses:us singleUse:su                            {: RESULT = new AstNode("uses", ""); RESULT.addGrandChildren(us); RESULT.addChild(su); :}
                      | singleUse:su                                    {: RESULT = new AstNode("uses", "", su); :}
                      ; 
methods             ::= methods:ms method:m								{: RESULT = new AstNode("methods", "");	RESULT.addGrandChildren(ms); RESULT.addChild(m); :} 
                      | method:m                                        {: RESULT = new AstNode("methods", "", m); :}
                      ;