/* Part of code from http://www2.cs.tum.edu/projekte/cup/examples.php */
package zr54.parser;

import java_cup.runtime.*;
import edu.cornell.cs.cs4120.util.*;
import polyglot.util.*;
import zr54.lexer.*;
import zr54.parser.*;
import zr54.typechecker.Type;
import zr54.main.XiException;

parser code {:
    public CodeWriterSExpPrinter printer;
    public boolean silent;
    public parser(CodeWriterSExpPrinter printer, String file, boolean silent){ this.printer = printer; this.file = file; this.silent = silent;}
    public String file;

    @Override
    public void syntax_error(Symbol cur_token) {
    	try{
      String errorMessage = ((Lexer)this.getScanner()).getErrorMessage();
      if(errorMessage != null) {
            
            XiException e = new XiException(cur_token, errorMessage, "Lexical");
            
//             writer.write(e.getLine()+":"+e.getColumn()+" error:"+e.getMessage());
             printer.printAtom(e.errorMessage(file));
           throw e;
          }
   	    	if (cur_token.value!=null){
        		Symbol tok = (Symbol) cur_token.value;
         	 	printer.printAtom(cur_token.left + ":" +
                	cur_token.right + " error:Unexpected token " + tok.value);
				throw new XiException(tok,"Unexpected token " + tok.value, "Syntax");
        	} else{
	            printer.printAtom(cur_token.left + ":" + cur_token.right +
    	        " error:Unexpected token " + LexerOutput.terminalName.get(cur_token.sym));
        	    throw new XiException(cur_token, "Unexpected token " +LexerOutput.terminalName.get(cur_token.sym), "Syntax"); 
	       }
    	}
    	catch(XiException e) {
      //printer.printAtom(e.errorMessage(file));
    		if(!silent)System.out.println(e.errorMessage(file));
    	}
    }
:}
/* NEVER DELETE ANY TERMINALS EVEN IF THERE ARE WARNINGS THAT THEY ARE NEVER USED!!! */
terminal Symbol IDENTIFIER, INTEGER_LITERAL, STRING_LITERAL, CHARACTER_LITERAL, BOOLEAN_LITERAL,
         LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK, SEMICOLON, COMMA, COLON, EQ,
         GT, LT, NOT, MULT, PLUS, MINUS, AND, OR, MOD, IF, EQEQ, GTEQ, LTEQ, NOTEQ,
         HIGHMULT, INT, BOOL, ELSE, WHILE, LENGTH, RETURN, DIV, USE, UNDERSCORE, LRBRACK, 
         CLASS, THIS, NEW, EXTENDS, BREAK, CONTINUE, DOT, NULL;

nonterminal AstNode program, singleUse, uses, arrayType, arrayTypeNonEmpty, type, typeNonEmpty,  argumentWithType, argumentWithTypeNonEmpty, multipleArgumentsWithSingleTypeNonEmpty, twoOrMoreIdentifies,
            argumentsWithType, optionalArgumentsWithType, functionReturnType,
            statements, optionalStatements, statement, typesList, assignment,
            ifStatement, whileStatement, nonEmptyBracket, nonEmptyBrackets,
            emptyBracket, emptyBrackets, newVariables,
            variable, newVariable, expressions, methods, method, arrayLiteral, optionalSemicolon,
            block, optionalReturn, minusExpression;
nonterminal AstNode expression, argument, arrayIndices, varArrayIndices, functionCall;    

//new for oXi
nonterminal AstNode classDef, classDefs, classField, classMethod, classFieldsMethods, newObject, fieldAccess;

precedence nonassoc ELSE;
precedence nonassoc EQ;
precedence left OR;
precedence left AND;
precedence left EQEQ, NOTEQ;
precedence left LT, LTEQ, GTEQ, GT;
precedence left PLUS, MINUS;
precedence left MULT, HIGHMULT, DIV, MOD;
precedence nonassoc NOT;


start with program;

//new for oXi 
classDefs           ::= classDefs:cs classDef:c {: RESULT = new DefaultNode("classDefs", null); RESULT.addGrandChildren(cs); RESULT.addChild(c); :}
                      | classDef:c {: RESULT = new DefaultNode("classDefs", null, c); :}          
                      ;

classDef			::= CLASS:c IDENTIFIER:id LBRACE:lb classFieldsMethods:fm RBRACE:rb 
						{: RESULT = new ClassNode("classDef", id); RESULT.addGrandChildren(fm); ((ClassNode) RESULT).findMethodsAndFields(); :}
           			  | CLASS:c IDENTIFIER:id EXTENDS IDENTIFIER:s LBRACE:lb classFieldsMethods:fm RBRACE:rb
           			    {: RESULT = new ClassNode("classDef", id); RESULT.addChild(new ClassNameNode("className", s)); RESULT.addGrandChildren(fm); ((ClassNode) RESULT).findMethodsAndFields(); :}
					  ;
					  
classFieldsMethods	::= classFieldsMethods:fm classMethod:m    {: RESULT = new DefaultNode("classFieldsMethods", null); RESULT.addGrandChildren(fm); RESULT.addChild(m); :}
						  | classFieldsMethods:fm classField:f {: RESULT = new DefaultNode("classFieldsMethods", null); RESULT.addGrandChildren(fm); RESULT.addChild(f); :}
						  |	classMethod:m	{: RESULT = new DefaultNode("classFieldsMethods", null, m); :}
						  | classField:f	{: RESULT = new DefaultNode("classFieldsMethods", null, f); :}
              | multipleArgumentsWithSingleTypeNonEmpty:m  {: RESULT = m; :}
						  ; 

classMethod         ::= IDENTIFIER:id LPAREN optionalArgumentsWithType:a RPAREN functionReturnType:r LBRACE:l optionalStatements:os optionalReturn:re RBRACE
                        {: RESULT = new ClassMethodNode("classMethod", id);
                           RESULT.addChild(a); RESULT.addChild(r);
                           RESULT.addChild(os);
                           if(os != null) os.addChild(re); else RESULT.addChild(re); :}
                      ;

classField			::= IDENTIFIER:id COLON type:t {: RESULT = new DeclarationNode("argumentWithType", id, t); :}
					  ;

fieldAccess         ::= IDENTIFIER:o DOT:d IDENTIFIER:f {: RESULT = new ClassFieldAccessNode("fieldAccess", d, new VariableNode("object", o), new ClassFieldNode("field", f)); :}
                      | functionCall:fc         DOT:d IDENTIFIER:f {: RESULT = new ClassFieldAccessNode("fieldAccess", d, fc, new ClassFieldNode("field", f)); :}
                      //| arrayIndices:ai         DOT IDENTIFIER {: RESULT = xxx; :}
                      | varArrayIndices:v  DOT:d IDENTIFIER:f {: RESULT = new ClassFieldAccessNode("fieldAccess", d, v, new ClassFieldNode("field", f)); :}
                      | fieldAccess:fa DOT:d IDENTIFIER:f {: RESULT = new ClassFieldAccessNode("fieldAccess", d, fa, new ClassFieldNode("field", f)); :}
                      | newObject:no DOT:d IDENTIFIER:f {: RESULT = new ClassFieldAccessNode("fieldAccess", d, no, new ClassFieldNode("field", f)); :}
                      | THIS:t DOT:d IDENTIFIER:f {: RESULT = new ClassFieldAccessNode("fieldAccess", d, new ThisNode("this", t), new ClassFieldNode("field", f)); :}
                      ;
newObject           ::= NEW:n IDENTIFIER:id 	 {: RESULT = new NewObjectNode("newObject", n, new ClassNameNode("className", id)); :}

                      ;
//the above are new for oXi


singleUse           ::= USE:u IDENTIFIER:id optionalSemicolon  {: RESULT = new DefaultNode("useSpecifier", null, new DefaultNode("USE", u), new DefaultNode("IDENTIFIER", id)); :}
                      ;

arrayType           ::= INT:i emptyBrackets:bs    {: bs.addChildLeftMost(new TypeNode("INT", i)); RESULT = bs; :}
                      | BOOL:b emptyBrackets:bs   {: bs.addChildLeftMost(new TypeNode("BOOL", b)); RESULT = bs; :}
                      | IDENTIFIER:t emptyBrackets:bs  {: bs.addChildLeftMost(new TypeNode("IDENTIFIER", t)); RESULT = bs; :}
                      ;
arrayTypeNonEmpty   ::= INT:i emptyBrackets:bs    {: bs.addChildLeftMost(new TypeNode("INT", i)); RESULT = bs; :}
                      | BOOL:b emptyBrackets:bs   {: bs.addChildLeftMost(new TypeNode("BOOL", b)); RESULT = bs; :}
                      | IDENTIFIER:t emptyBrackets:bs  {: bs.addChildLeftMost(new TypeNode("IDENTIFIER", t)); RESULT = bs; :}
                      | INT:i nonEmptyBrackets:bs    {: bs.addChildLeftMost(new TypeNode("INT", i)); RESULT = bs; :}
                      | BOOL:b nonEmptyBrackets:bs   {: bs.addChildLeftMost(new TypeNode("BOOL", b)); RESULT = bs; :}
                      | IDENTIFIER:t nonEmptyBrackets:bs {: bs.addChildLeftMost(new TypeNode("IDENTIFIER", t)); RESULT = bs; :}
                      ;
arrayLiteral        ::= LBRACE:l expressions:es RBRACE          {: RESULT = new ArrayLiteralNode("arrayLiteral", l); RESULT.addGrandChildren(es); :}
                      | LBRACE:l expressions:es COMMA RBRACE    {: RESULT = new ArrayLiteralNode("arrayLiteral", l); RESULT.addGrandChildren(es); :}
                      | LBRACE:l RBRACE  {: RESULT = new ArrayLiteralNode("arrayLiteral", l); :}
                      ;

emptyBracket        ::= LBRACK:lb RBRACK                {: RESULT = new TypeNode("bracket", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), new DefaultNode("emptyBrack", null));  :}
                      ;
emptyBrackets       ::= emptyBracket:b emptyBrackets:bs   {: RESULT = new TypeNode("brackets", b.symbol, bs); RESULT.addGrandChildren(b); :}
                      | emptyBracket:b               {: RESULT = b; :}
                      ;
nonEmptyBracket     ::= LBRACK:lb expression:es  RBRACK {: RESULT = new TypeNode("bracket", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), es); :}
                      ;
nonEmptyBrackets    ::= nonEmptyBracket:b emptyBrackets:bs   {: RESULT = new TypeNode("brackets", b.symbol, bs); RESULT.addGrandChildren(b); :}
                      | nonEmptyBracket:b nonEmptyBrackets:bs   {: RESULT = new TypeNode("brackets", b.symbol, bs); RESULT.addGrandChildren(b); :}
                      | nonEmptyBracket:b               {: RESULT = b; :}
                      ;
                    
type                ::= arrayType:a     {: RESULT = a; :}
                      | INT:i             {: RESULT = new TypeNode("INT", i); :}
                      | BOOL:b            {: RESULT = new TypeNode("BOOL", b); :}
                      | IDENTIFIER:t	  {: RESULT = new TypeNode("IDENTIFIER", t); :}
                      ;
typeNonEmpty        ::= arrayTypeNonEmpty:a     {: RESULT = a; :}
                      | INT:i             {: RESULT = new TypeNode("INT", i); :}
                      | BOOL:b            {: RESULT = new TypeNode("BOOL", b); :}
                      | IDENTIFIER:t    {: RESULT = new TypeNode("IDENTIFIER", t); :}
                      ;
argumentWithType    ::= IDENTIFIER:id COLON type:t  {: RESULT = new DeclarationNode("argumentWithType", id, t); :}
                      ;
argumentWithTypeNonEmpty::=IDENTIFIER:id COLON typeNonEmpty:t  {: RESULT = new DeclarationNode("argumentWithType", id, t); :}
                      ;
argumentsWithType   ::= argumentsWithType:as COMMA argumentWithType:a {: RESULT = new DefaultNode("argumentsWithType", null); RESULT.addGrandChildren(as); RESULT.addChild(a); :}
                      | argumentWithType:a                            {: RESULT = new DefaultNode("argumentsWithType", null, a); :}
                      ;
multipleArgumentsWithSingleTypeNonEmpty::= twoOrMoreIdentifies:ids COLON typeNonEmpty:t {: RESULT = new MultiDeclarationNode("multiDeclaration", null, ids, t); :}
;
twoOrMoreIdentifies ::= IDENTIFIER:id1 COMMA IDENTIFIER:id2 {: RESULT = new DefaultNode("identifiers", null, new VariableNode("variable", id1), new VariableNode("variable", id2)); :}
                      | twoOrMoreIdentifies:ids COMMA IDENTIFIER:id {: RESULT = ids; ids.addChild(new VariableNode("variable", id)); :}
                      ;
argument            ::= BOOLEAN_LITERAL:bl      {: RESULT = new LiteralExpr("BOOLEAN_LITERAL", new Symbol(bl.sym, bl.left, bl.right, bl.value), Type.BOOL, 0); :}
                      | INTEGER_LITERAL:il      {: RESULT = new LiteralExpr("INTEGER_LITERAL", new Symbol(il.sym, il.left, il.right, il.value), Type.INT, 0); :}
                      | CHARACTER_LITERAL:cl    {: RESULT = new LiteralExpr("CHARACTER_LITERAL", new Symbol(cl.sym, cl.left, cl.right, cl.value), Type.INT, 0); :}
                      | STRING_LITERAL:sl       {: RESULT = new LiteralExpr("STRING_LITERAL", new Symbol(sl.sym, sl.left, sl.right, sl.value), Type.INT, 1); :}
                      | IDENTIFIER:id           {: RESULT = new VariableNode("IDENTIFIER", id); :}
                      | functionCall:fc         {: RESULT = fc; :}
                      | arrayLiteral:al         {: RESULT = al; :}
                      | arrayIndices:ai         {: RESULT = ai; :}
                      | varArrayIndices:v  {: RESULT = v; :}
                      | fieldAccess:fa {: RESULT = fa; :}
                      | newObject:no {: RESULT = no; :}
                      | THIS:t {: RESULT = new ThisNode("this", t); :}
                      | NULL:n {: RESULT = new NullNode("null", n); :}
                      ;

arrayIndices        ::= arrayIndices:ai LBRACK:lb expression:a RBRACK  {: RESULT = new ArrayIndicesNode("arrayIndices", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), ai, a); :}
                      
                     
                      | STRING_LITERAL:sl  LBRACK:lb expression:a RBRACK    {: RESULT = new ArrayIndicesNode("arrayIndices", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), new LiteralExpr("STRING_LITERAL", new Symbol(sl.sym, sl.left, sl.right, sl.value), Type.INT, 1), a); :}
                      | arrayLiteral:al  LBRACK:lb expression:a RBRACK    {: RESULT = new ArrayIndicesNode("arrayIndices", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), al, a); :}
                      | LPAREN expression:e RPAREN  LBRACK:lb expression:a RBRACK    {: RESULT = new ArrayIndicesNode("arrayIndices", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), e, a); :}
                      
                      ;
varArrayIndices     ::= IDENTIFIER:id LBRACK:lb expression:a RBRACK    {: RESULT = new ArrayIndicesNode("arrayIndices", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), new VariableNode("IDENTIFIER", id), a); :}
                      | functionCall:fc  LBRACK:lb expression:a RBRACK    {: RESULT = new ArrayIndicesNode("arrayIndices", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), fc, a); :}
                      | varArrayIndices:v LBRACK:lb expression:a RBRACK {: RESULT = new ArrayIndicesNode("arrayIndices", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), v, a); :}
                      | fieldAccess:fa LBRACK:lb expression:a RBRACK {: RESULT = new ArrayIndicesNode("arrayIndices", new Symbol(sym.LRBRACK, lb.left, lb.right, "[]"), fa, a);:}
                      ;
functionReturnType  ::= COLON typesList:tl    {: RESULT = new DefaultNode("functionReturnType", null); RESULT.addGrandChildren(tl); :}
                      |                       {: RESULT = new DefaultNode("forceParen", null); :}
                      ;

typesList           ::= typesList:tl COMMA type:t   {: RESULT = new DefaultNode("typesList", null); RESULT.addGrandChildren(tl); RESULT.addChild(t); :}
                      | type:t                      {: RESULT = new DefaultNode("typesList", null); RESULT.addChild(t); :}
                      ;


method              ::= IDENTIFIER:id LPAREN optionalArgumentsWithType:a RPAREN functionReturnType:r LBRACE:l optionalStatements:os optionalReturn:re RBRACE
                        {: RESULT = new MethodNode("method", id, l);
                           RESULT.addChild(a); RESULT.addChild(r);
                           RESULT.addChild(os);
                           if(os != null) os.addChild(re); else RESULT.addChild(re); :}
                      | classDef:cd {: RESULT =  cd; :}
                      | argumentWithTypeNonEmpty:a  {: RESULT = a; :}
                      | multipleArgumentsWithSingleTypeNonEmpty:m  {: RESULT = m; :}
                      | argumentWithType:a EQ:eq expression:e {: RESULT = new AssignStmtNode("assignment", eq, a, e); :}
                      ;

optionalStatements  ::= statements:s {: RESULT = s; :}
                      |	             {: RESULT = new DefaultNode("forceParen", null); :}
                      ;

optionalArgumentsWithType ::=  argumentsWithType:a {: RESULT = a; :}
                            |                      {: RESULT = new DefaultNode("forceParen", null); :}
                            ;

statements  ::= statements:ms statement:s     {: RESULT = new StmtsNode("statements", null); RESULT.addGrandChildren(ms); RESULT.addChild(s); :}
                      | statement:s           {: RESULT = new StmtsNode("statements", null); RESULT.addChild(s); :}
                      ;

statement           ::= functionCall:f optionalSemicolon         {: RESULT = new FunctionCallAsStmt(f); :}
                      | assignment:a optionalSemicolon           {: RESULT = a; :}
                      | ifStatement:s                            {: RESULT = s; :}
                      | whileStatement:s                         {: RESULT = s; :}
                      | argumentWithTypeNonEmpty:a optionalSemicolon     {: RESULT = a; :}
                      | block: b                                 {: RESULT = b; :}
                      | BREAK: b  {: RESULT = new BreakContinueNode("break", b); :}
                      | CONTINUE:c  {: RESULT = new BreakContinueNode("continue", c); :}
                      | multipleArgumentsWithSingleTypeNonEmpty:m  {: RESULT = m; :}
                      ;

optionalReturn      ::= RETURN:ret expressions:e optionalSemicolon {: RESULT = new ReturnNode("optionalReturn", ret); RESULT.addGrandChildren(e); :}
                      | RETURN:ret optionalSemicolon {: RESULT = new ReturnNode("optionalReturn", ret); :}
                      |
                      ;

optionalSemicolon   ::= SEMICOLON
                      |
                      ;

ifStatement         ::= IF:i LPAREN expression:e RPAREN statement:s1 ELSE statement:s2  {: RESULT = new IfElseStmtNode("ifStatement", i, e, s1, s2); :}
                      | IF:i LPAREN expression:e RPAREN statement:s                     {: RESULT = new IfWhileStmtNode("ifStatement", i, e, s); :}
                      ;

whileStatement      ::= WHILE:w LPAREN expression:e RPAREN statement:s  {: RESULT = new IfWhileStmtNode("whileStatement", w, e, s); :}
                      ;

assignment          ::= newVariables:vs COMMA newVariable:v EQ:eq expression:e   {: DefaultNode node = new MultiVariableNode("variables", null);
                                                                           node.addGrandChildren(vs); node.addChild(v);
                                                                           RESULT = new AssignStmtNode("assignment", eq, node, e); :}
                      | variable:v EQ:eq expression:e                      {: RESULT = new AssignStmtNode("assignment", eq, v, e); :}
                      ;


newVariables       ::= newVariables:vs COMMA newVariable:v     {: RESULT = new DefaultNode("variables", null); RESULT.addGrandChildren(vs); RESULT.addChild(v); :}
                      | newVariable:v                        {: RESULT = new DefaultNode("variables", null); RESULT.addChild(v); :}
                      ;
variable            ::= UNDERSCORE:us                     {: RESULT = new UnderscoreNode("UNDERSCORE", us); :}
                      | IDENTIFIER:id                     {: RESULT = new VariableNode("IDENTIFIER", id); :}
                      | argumentWithType:a                {: RESULT = a; :}
                      | varArrayIndices:a                 {: RESULT = a; :}
                      | fieldAccess:fa 					  {: RESULT = fa; :}
                      ;
newVariable       ::= UNDERSCORE:us                     {: RESULT = new UnderscoreNode("UNDERSCORE", us); :}
                     
                      | argumentWithType:a                {: RESULT = a; :}
                      
                      ;
expression          ::= expression:e1 OR:or expression:e2				 {: RESULT = new AndOrNode("OR", or, e1, e2); :}
		                  | expression:e1 AND:and expression:e2			 {: RESULT = new AndOrNode("AND", and, e1, e2); :}
		                  | expression:e1 EQEQ:eq expression:e2			 {: RESULT = new EqNotEqNode("EQEQ", eq, e1, e2); :}
		                  | expression:e1 NOTEQ:neq expression:e2		 {: RESULT = new EqNotEqNode("NOTEQ", neq, e1, e2); :}
		                  | expression:e1 LT:lt expression:e2				 {: RESULT = new GtLtGeLeNode("LT", lt, e1, e2); :}
		                  | expression:e1 LTEQ:leq expression:e2		 {: RESULT = new GtLtGeLeNode("LTEQ", leq, e1, e2); :}
		                  | expression:e1 GTEQ:geq expression:e2		 {: RESULT = new GtLtGeLeNode("GTEQ", geq, e1, e2); :}
                      | expression:e1 GT:gt expression:e2				 {: RESULT = new GtLtGeLeNode("GT", gt, e1, e2); :}
                      |	expression:e1 PLUS:pl expression:e2			 {: RESULT = new AddIntBinaryExprNode("PLUS", pl, e1, e2); :}
                      | expression:e1 MINUS:mi expression:e2		 {: RESULT = new IntBinaryExprNode("MINUS", mi, e1, e2); :}
                      | expression:e1 MULT:mu expression:e2			 {: RESULT = new IntBinaryExprNode("MULT", mu, e1, e2); :}
                      | expression:e1 HIGHMULT:hm expression:e2	 {: RESULT = new IntBinaryExprNode("HIGHMULT", hm, e1, e2); :}
                      | expression:e1 DIV:di expression:e2			 {: RESULT = new IntBinaryExprNode("DIV", di, e1, e2); :}
                      | expression:e1 MOD:md expression:e2			 {: RESULT = new IntBinaryExprNode("MOD", md, e1, e2); :}
                      | LPAREN expression:e RPAREN				       {: RESULT = e; :}
                      | argument:a                   				     {: RESULT = a; :}
                      | minusExpression:m {: RESULT = m; :}
                      | NOT:n expression:e		                   {: RESULT = new NotNode("NOT", n, e); :}
                      ;
minusExpression     ::= MINUS:mi LPAREN expression:e RPAREN      {: RESULT = new MinusNode("MINUS", mi, e); :}
                      | MINUS:mi argument:a                      {: RESULT = new MinusNode("MINUS", mi, a); :}
                      | MINUS:mi minusExpression:m               {: RESULT = new MinusNode("MINUS", mi, m); :}
                      ;
expressions         ::= expression:e                             {: RESULT = new DefaultNode("expressions", null, e); :}
                      | expressions:es COMMA expression:e        {: RESULT = new DefaultNode("expressions", null); RESULT.addGrandChildren(es); RESULT.addChild(e); :}
                      ;

functionCall        ::= IDENTIFIER:id LPAREN expressions:es RPAREN    {: RESULT = new FunctionCallNode("functionCall", id); RESULT.addGrandChildren(es); :}
                      | IDENTIFIER:id LPAREN RPAREN                   {: RESULT = new FunctionCallNode("forceParen", id);:}
                      | LENGTH:l LPAREN expression:e RPAREN            {: RESULT = new LengthNode("length", l, e); :}
                      
                      | functionCall:fc         DOT:d IDENTIFIER:f  LPAREN expressions:es RPAREN {: RESULT = new ClassMethodCallNode("classMethodCall", f, fc, es); :}
                      //| arrayIndices:ai         DOT IDENTIFIER  LPAREN expressions:es RPAREN {:xxx :}
                      | varArrayIndices:v  DOT:d IDENTIFIER:f  LPAREN expressions:es RPAREN {: RESULT = new ClassMethodCallNode("classMethodCall", f, v, es); :}
                      | fieldAccess:fa DOT:d IDENTIFIER:f  LPAREN expressions:es RPAREN {: RESULT = new ClassMethodCallNode("classMethodCall", f, fa, es); :}
                      | newObject:no DOT:d IDENTIFIER:f  LPAREN expressions:es RPAREN {: RESULT = new ClassMethodCallNode("classMethodCall", f, no, es); :}
                      | THIS:t DOT IDENTIFIER:f  LPAREN expressions:es RPAREN {: RESULT = new ClassMethodCallNode("classMethodCall", f, new ThisNode("this", t), es); :}
                      | functionCall:fc         DOT:d IDENTIFIER:f  LPAREN RPAREN    {: RESULT = new ClassMethodCallNode("classMethodCall", f, fc); :}
                      //| arrayIndices:ai         DOT IDENTIFIER  LPAREN RPAREN    {:xxx :}
                      | varArrayIndices:v  DOT:d IDENTIFIER:f  LPAREN RPAREN    {: RESULT = new ClassMethodCallNode("classMethodCall", f, v); :}
                      | fieldAccess:fa DOT:d IDENTIFIER:f  LPAREN RPAREN    {: RESULT = new ClassMethodCallNode("classMethodCall", f, fa); :}
                      | newObject:no DOT:d IDENTIFIER:f  LPAREN RPAREN    {: RESULT = new ClassMethodCallNode("classMethodCall", f, no); :}
                      | THIS:t DOT IDENTIFIER:f  LPAREN RPAREN    {: RESULT = new ClassMethodCallNode("classMethodCall", f, new ThisNode("this", t)); :}
                      
                      ;

program             ::= uses:us  methods:ms   {: RESULT = new DefaultNode("program", null, us, ms); :}
//TODO: not complete					
                      
                      | methods:ms            {: RESULT = new DefaultNode("program", null, new DefaultNode("forceParen", null), ms); :}
                      | error:e               {:  :}
                      ;

uses                ::= uses:us singleUse:su  {: RESULT = new DefaultNode("uses", null); RESULT.addGrandChildren(us); RESULT.addChild(su); :}
                      | singleUse:su          {: RESULT = new DefaultNode("uses", null, su); :}
                      ;

methods             ::= methods:ms method:m   {: RESULT = new DefaultNode("methods", null); RESULT.addGrandChildren(ms); RESULT.addChild(m); :}
                      | method:m              {: RESULT = new DefaultNode("methods", null, m); :}
                      ;

block               ::= LBRACE:l optionalStatements:os optionalReturn:re RBRACE      {: RESULT = new BlockNode("block", l);  if(!os.name.equals("forceParen")) {if(re != null) os.addChild(re); RESULT.addChild(os);} else { if(re != null) RESULT.addChild(re); else RESULT.addChild(os); }:}
                      ;
